# Auto-generated by tools/sync_config_docstrings.py — do not edit by hand.

from __future__ import annotations

from ..density_core import _DensityProfile

from inversion_fbpic.lib.density_core import _DensityProfile, DensityCallable
from typing import ClassVar, Literal

SkewMode = Literal['auto', 'finite_supergaussian', 'exponential', 'saturated']

class _FiniteSkewedProfile(_DensityProfile):
    """Shared extent metadata and post-composition skew for density profiles.

    Args:
        nominal_density: (float) [m^-3] Baseline (nominal) plasma density in m^-3 used to scale
            the relative profile returned by `build_density_function` (which is normalized to 1).
        p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
        p_nr: (int) Number of macroparticles per gridcell along the radial direction.
        p_nt: (int) Number of macroparticles per gridcell along the angular direction.
        species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
            If None, the plasma is assumed to be fully ionized and no ionization is considered.
            If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
            Defaults to Hydrogen.
        ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
            Defaults to unionized (ionization level 0).
        p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
        elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
        elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
            Defaults to None.
        ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
        ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Defaults to None."""
    start_position: float
    skew_rate: float
    skew_mode: SkewMode
    def __init__(
        self,
        *,
        nominal_density: float,
        p_nz: int,
        p_nr: int,
        p_nt: int,
        species: str | None = 'H',
        ionization: int | None = 0,
        p_rmax: float | None = None,
        elec_name: str | None = None,
        elec_select: dict[str, list[float | None]] | None = None,
        ion_name: str | None = None,
        ion_select: dict[str, list[float | None]] | None = None,
        start_position: float,
        skew_rate: float = 0.0,
        skew_mode: SkewMode = 'auto',
    ) -> None:
        """Shared extent metadata and post-composition skew for density profiles.

        Args:
            nominal_density: (float) [m^-3] Baseline (nominal) plasma density in m^-3 used to scale
                the relative profile returned by `build_density_function` (which is normalized to 1).
            p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
            p_nr: (int) Number of macroparticles per gridcell along the radial direction.
            p_nt: (int) Number of macroparticles per gridcell along the angular direction.
            species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
                If None, the plasma is assumed to be fully ionized and no ionization is considered.
                If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
                Defaults to Hydrogen.
            ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
                Defaults to unionized (ionization level 0).
            p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
            elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
            elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
                Defaults to None.
            ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
            ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Defaults to None."""
    def get_z_extent(self) -> tuple[float, float]:
        ...
    def get_r_extent(self) -> float | None:
        ...
    def build_density_function(self) -> DensityCallable:
        ...

class GenericConicalTarget(_FiniteSkewedProfile):
    """Target with finite extent metadata composed from a main profile and fringes.

    ``main_profile_parameters`` and ``fringe_profile_parameters`` are validated
    dictionaries for the selected type. Supported main types are
    ``supergaussian``, ``cosine_squared_flattop``, ``power_law_flattop``, and
    ``lorentzian_flattop``.
    Supported fringe types are ``supergaussian``, ``cosine_squared``,
    ``power_law``, and ``lorentzian``.
    Skew is applied once after adding every selected component.

    Args:
        nominal_density: (float) [m^-3] Baseline (nominal) plasma density in m^-3 used to scale
            the relative profile returned by `build_density_function` (which is normalized to 1).
        p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
        p_nr: (int) Number of macroparticles per gridcell along the radial direction.
        p_nt: (int) Number of macroparticles per gridcell along the angular direction.
        species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
            If None, the plasma is assumed to be fully ionized and no ionization is considered.
            If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
            Defaults to Hydrogen.
        ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
            Defaults to unionized (ionization level 0).
        p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
        elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
        elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
            Defaults to None.
        ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
        ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Defaults to None.
        start_position: (float) [m] Longitudinal start of the full target extent metadata. The composed density remains continuously evaluable outside this interval.
        skew_rate: (float) [m^-1] |OPTIONAL| Longitudinal skew rate applied after combining components. It is the centroid log-density slope for every skew mode. Defaults to 0.0.
        skew_mode: (Literal[str]) |OPTIONAL| Skew equation. auto resolves to saturated for any Lorentzian component or SuperGaussian with beta <= 1; otherwise it resolves to finite_supergaussian. saturated approaches reciprocal finite factors alpha and 1/alpha, where alpha is derived from skew_rate and profile extent. exponential preserves the legacy multiplier. Defaults to auto.
        main_profile_type: (Literal[str]) Type of the centered main profile.
        main_profile_parameters: (dict[str, float]) Parameters for the main profile type.
        fringe_profile_type: (Literal[str]|None) |OPTIONAL| Type of the fringe profile. Defaults to None.
        fringe_profile_parameters: (dict[str, float]) |OPTIONAL| Parameters for the fringe profile type. Defaults to {}.
        fringe_center_offset: (float|None) [m] |OPTIONAL| Positive distance from the main center to each fringe center. Required when a fringe type is selected.
        fringe_relative_height: (float) |OPTIONAL| Amplitude of every fringe relative to the main profile. Fringe support is included where its amplitude relative to the unit main lobe is at or above the component cutoff. Defaults to 1.0.
        fringe_side: (Literal[str]) |OPTIONAL| Select ``left``, ``right``, or ``both`` fringes. Defaults to ``both``."""
    SUBCLASS: ClassVar[str]
    main_profile_type: Literal['supergaussian', 'cosine_squared_flattop', 'power_law_flattop', 'lorentzian_flattop']
    main_profile_parameters: dict[str, float]
    fringe_profile_type: Literal['supergaussian', 'cosine_squared', 'power_law', 'lorentzian'] | None
    fringe_profile_parameters: dict[str, float]
    fringe_center_offset: float | None
    fringe_relative_height: float
    fringe_side: Literal['left', 'right', 'both']
    centroid: float
    def __init__(
        self,
        *,
        nominal_density: float,
        p_nz: int,
        p_nr: int,
        p_nt: int,
        species: str | None = 'H',
        ionization: int | None = 0,
        p_rmax: float | None = None,
        elec_name: str | None = None,
        elec_select: dict[str, list[float | None]] | None = None,
        ion_name: str | None = None,
        ion_select: dict[str, list[float | None]] | None = None,
        start_position: float,
        skew_rate: float = 0.0,
        skew_mode: SkewMode = 'auto',
        main_profile_type: Literal['supergaussian', 'cosine_squared_flattop', 'power_law_flattop', 'lorentzian_flattop'],
        main_profile_parameters: dict[str, float],
        fringe_profile_type: Literal['supergaussian', 'cosine_squared', 'power_law', 'lorentzian'] | None = None,
        fringe_profile_parameters: dict[str, float] = ...,
        fringe_center_offset: float | None = None,
        fringe_relative_height: float = 1.0,
        fringe_side: Literal['left', 'right', 'both'] = 'both',
    ) -> None:
        """Target with finite extent metadata composed from a main profile and fringes.

        ``main_profile_parameters`` and ``fringe_profile_parameters`` are validated
        dictionaries for the selected type. Supported main types are
        ``supergaussian``, ``cosine_squared_flattop``, ``power_law_flattop``, and
        ``lorentzian_flattop``.
        Supported fringe types are ``supergaussian``, ``cosine_squared``,
        ``power_law``, and ``lorentzian``.
        Skew is applied once after adding every selected component.

        Args:
            nominal_density: (float) [m^-3] Baseline (nominal) plasma density in m^-3 used to scale
                the relative profile returned by `build_density_function` (which is normalized to 1).
            p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
            p_nr: (int) Number of macroparticles per gridcell along the radial direction.
            p_nt: (int) Number of macroparticles per gridcell along the angular direction.
            species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
                If None, the plasma is assumed to be fully ionized and no ionization is considered.
                If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
                Defaults to Hydrogen.
            ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
                Defaults to unionized (ionization level 0).
            p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
            elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
            elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
                Defaults to None.
            ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
            ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Defaults to None.
            start_position: (float) [m] Longitudinal start of the full target extent metadata. The composed density remains continuously evaluable outside this interval.
            skew_rate: (float) [m^-1] |OPTIONAL| Longitudinal skew rate applied after combining components. It is the centroid log-density slope for every skew mode. Defaults to 0.0.
            skew_mode: (Literal[str]) |OPTIONAL| Skew equation. auto resolves to saturated for any Lorentzian component or SuperGaussian with beta <= 1; otherwise it resolves to finite_supergaussian. saturated approaches reciprocal finite factors alpha and 1/alpha, where alpha is derived from skew_rate and profile extent. exponential preserves the legacy multiplier. Defaults to auto.
            main_profile_type: (Literal[str]) Type of the centered main profile.
            main_profile_parameters: (dict[str, float]) Parameters for the main profile type.
            fringe_profile_type: (Literal[str]|None) |OPTIONAL| Type of the fringe profile. Defaults to None.
            fringe_profile_parameters: (dict[str, float]) |OPTIONAL| Parameters for the fringe profile type. Defaults to {}.
            fringe_center_offset: (float|None) [m] |OPTIONAL| Positive distance from the main center to each fringe center. Required when a fringe type is selected.
            fringe_relative_height: (float) |OPTIONAL| Amplitude of every fringe relative to the main profile. Fringe support is included where its amplitude relative to the unit main lobe is at or above the component cutoff. Defaults to 1.0.
            fringe_side: (Literal[str]) |OPTIONAL| Select ``left``, ``right``, or ``both`` fringes. Defaults to ``both``."""

class PowerLawFlattop(_FiniteSkewedProfile):
    """Finite flattop with a second-order-continuous power-law edge.

    The relative density is one across the central flattop. On each edge it
    follows ``(1 - s**transition_exponent)**3`` for normalized coordinate
    ``s`` from zero to one. Requiring ``transition_exponent > 2`` makes the
    profile and its first two derivatives continuous at the flattop boundary;
    the cubic outer factor makes the same derivatives vanish at finite support.

    Args:
        nominal_density: (float) [m^-3] Baseline (nominal) plasma density in m^-3 used to scale
            the relative profile returned by `build_density_function` (which is normalized to 1).
        p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
        p_nr: (int) Number of macroparticles per gridcell along the radial direction.
        p_nt: (int) Number of macroparticles per gridcell along the angular direction.
        species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
            If None, the plasma is assumed to be fully ionized and no ionization is considered.
            If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
            Defaults to Hydrogen.
        ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
            Defaults to unionized (ionization level 0).
        p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
        elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
        elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
            Defaults to None.
        ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
        ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Defaults to None.
        start_position: (float) [m] Longitudinal start of the profile extent metadata. The density remains continuously evaluable outside this interval.
        skew_rate: (float) [m^-1] |OPTIONAL| Longitudinal skew rate. It is the centroid log-density slope for every skew mode. Defaults to 0.0.
        skew_mode: (Literal[str]) |OPTIONAL| Skew equation. auto resolves to finite_supergaussian for this compact-edge profile. saturated approaches reciprocal finite factors derived from skew_rate without adding a Gaussian tail envelope. exponential preserves the legacy multiplier. Defaults to auto.
        flattop_width: (float) [m] Full width of the constant-density central region.
        transition_length: (float) [m] Length of each power-law edge transition.
        transition_exponent: (float) Power-law exponent. Must be greater than 2."""
    SUBCLASS: ClassVar[str]
    flattop_width: float
    transition_length: float
    transition_exponent: float
    centroid: float
    def __init__(
        self,
        *,
        nominal_density: float,
        p_nz: int,
        p_nr: int,
        p_nt: int,
        species: str | None = 'H',
        ionization: int | None = 0,
        p_rmax: float | None = None,
        elec_name: str | None = None,
        elec_select: dict[str, list[float | None]] | None = None,
        ion_name: str | None = None,
        ion_select: dict[str, list[float | None]] | None = None,
        start_position: float,
        skew_rate: float = 0.0,
        skew_mode: SkewMode = 'auto',
        flattop_width: float,
        transition_length: float,
        transition_exponent: float,
    ) -> None:
        """Finite flattop with a second-order-continuous power-law edge.

        The relative density is one across the central flattop. On each edge it
        follows ``(1 - s**transition_exponent)**3`` for normalized coordinate
        ``s`` from zero to one. Requiring ``transition_exponent > 2`` makes the
        profile and its first two derivatives continuous at the flattop boundary;
        the cubic outer factor makes the same derivatives vanish at finite support.

        Args:
            nominal_density: (float) [m^-3] Baseline (nominal) plasma density in m^-3 used to scale
                the relative profile returned by `build_density_function` (which is normalized to 1).
            p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
            p_nr: (int) Number of macroparticles per gridcell along the radial direction.
            p_nt: (int) Number of macroparticles per gridcell along the angular direction.
            species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
                If None, the plasma is assumed to be fully ionized and no ionization is considered.
                If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
                Defaults to Hydrogen.
            ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
                Defaults to unionized (ionization level 0).
            p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
            elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
            elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
                Defaults to None.
            ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
            ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Defaults to None.
            start_position: (float) [m] Longitudinal start of the profile extent metadata. The density remains continuously evaluable outside this interval.
            skew_rate: (float) [m^-1] |OPTIONAL| Longitudinal skew rate. It is the centroid log-density slope for every skew mode. Defaults to 0.0.
            skew_mode: (Literal[str]) |OPTIONAL| Skew equation. auto resolves to finite_supergaussian for this compact-edge profile. saturated approaches reciprocal finite factors derived from skew_rate without adding a Gaussian tail envelope. exponential preserves the legacy multiplier. Defaults to auto.
            flattop_width: (float) [m] Full width of the constant-density central region.
            transition_length: (float) [m] Length of each power-law edge transition.
            transition_exponent: (float) Power-law exponent. Must be greater than 2."""
