# Auto-generated by tools/sync_config_docstrings.py — do not edit by hand.

from __future__ import annotations

from ..density_core import _DensityProfile

from inversion_fbpic.lib.density_core import _DensityProfile, DensityCallable
from pathlib import Path
from scipy.interpolate import RegularGridInterpolator
from typing import ClassVar, Literal

class InterpolateFromH5Profile(_DensityProfile):
    """Longitudinal density profile interpolated from an HDF5 density dataset.

    File structure:
        The HDF5 file must contain a root-level N-dimensional density dataset named
        by ``density_name``, with finite values. Its ``DIMENSION_LABELS`` attribute
        must contain one unique label per dimension in dataset-shape order. For each
        label, the file must contain a root-level one-dimensional coordinate dataset
        with at least two values, the same length as its corresponding density
        dimension, and finite, strictly increasing values. Density values must be
        finite and non-negative.

        ``lineout_axis`` can select one coordinate varied to create the longitudinal
        lineout, or define a parameterized linear path through multiple coordinates.
        In the path form, each coordinate follows
        ``coordinate(t) = origin + coefficient * t``.
        ``interpolation_points`` must provide exactly one in-bounds position for every
        labeled coordinate not included in the lineout. The selected lineout is
        normalized to its positive peak, which becomes ``nominal_density``; values
        outside the lineout coordinate range evaluate to zero.

        For example, ``my_profile.h5`` contains a root-level ``density`` dataset
        with ``DIMENSION_LABELS = ["z_m", "x_mm", "pressure_bar"]`` and coordinate
        datasets named ``z_m``, ``x_mm``, and ``pressure_bar``. A lineout can use
        ``lineout_axis="z_m"`` with
        ``interpolation_points={"x_mm": 2.0, "pressure_bar": 1.0}``, or an oblique
        ``x_mm``-``z_m`` line with
        ``lineout_axis={"z_m": {"origin": 0.0, "coefficient": 1 / sqrt(2)},
        "x_mm": {"origin": 2.0, "coefficient": 1.0e-3 / sqrt(2)}}`` and
        ``interpolation_points={"pressure_bar": 1.0}``. The user is responsible for
        choosing coefficients with compatible units.

    Args:
        p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
        p_nr: (int) Number of macroparticles per gridcell along the radial direction.
        p_nt: (int) Number of macroparticles per gridcell along the angular direction.
        species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
            If None, the plasma is assumed to be fully ionized and no ionization is considered.
            If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
            Defaults to Hydrogen.
        ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
            Defaults to unionized (ionization level 0).
        p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
        elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
        elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
            Defaults to None.
        ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
        ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Defaults to None.
        filename: (str | Path) Path to the HDF5 file. Config-file serialization
            records it relative to the config file, including ``..`` segments,
            so a config and its referenced data can be relocated together.
        density_name: (str) Name of the multidimensional density dataset.
        neutral: (bool) |OPTIONAL| Whether the data is of the neutral atomic density or of the ionized electron density. Defaults to True.
        lineout_axis: (str | dict[str, dict[str, float]]) Coordinate dataset varied to form the longitudinal lineout, or parameterized linear path definitions. In the dictionary form, every key is a coordinate dataset and its value must contain finite ``origin`` and ``coefficient`` values defining ``coordinate(t) = origin + coefficient * t``. At least one coefficient must be nonzero; zero coefficients keep their coordinate fixed at its origin. The returned density function uses the sampled ``t`` coordinate after applying ``centering_mode`` and ``longitudinal_offset``.
        centroid_axis: (str | None) |OPTIONAL| Coordinate dataset used to calculate the density-weighted centroid for ``centering_mode="centroid"``. If provided, this axis is varied while other parameterized-linear-path axes are fixed at their origins and remaining axes are fixed by ``interpolation_points``. It must be included in ``lineout_axis`` with a nonzero coefficient so its centroid can be converted to the lineout parameter. Defaults to None, which uses the selected lineout.
        density_scale: (float) |OPTIONAL| Scalar multiple to apply to the density. Defaults to 1.0.
        interpolation_points: (dict[str, float]) |OPTIONAL| Positions for every other coordinate axis. Defaults to {}.
        longitudinal_offset: (float) [m] |OPTIONAL| Offset applied to the lineout coordinates. Defaults to 0.0.
        density_cutoff_ratio: (float) |OPTIONAL| Relative-to-peak cutoff used to determine the longitudinal extent. Defaults to 1e-3.
        centering_mode: (Literal[str]) |OPTIONAL| Density centering method.
            If `'centroid'`, the density-weighted centroid will be located at `z=longitudinal_offset`.
            If `'left'`, the cutoff-derived left extent will be located at `z=longitudinal_offset`.
            If `'right'`, the cutoff-derived right extent will be located at `z=longitudinal_offset`.
            Defaults to `'left'`.
        nominal_density: (float) [m^-3] |NOT REFERENCED| The peak density for this profile. This quantity is determined by the dataset used."""
    SUBCLASS: ClassVar[str]
    nominal_density: float
    filename: str | Path
    density_name: str
    neutral: bool
    lineout_axis: str | dict[str, dict[str, float]]
    centroid_axis: str | None
    density_scale: float
    interpolation_points: dict[str, float]
    longitudinal_offset: float
    density_cutoff_ratio: float
    centering_mode: Literal['centroid', 'left', 'right']
    lineout: RegularGridInterpolator
    centroid: float
    z_extent: tuple[float, float]
    def __init__(
        self,
        *,
        p_nz: int,
        p_nr: int,
        p_nt: int,
        species: str | None = 'H',
        ionization: int | None = 0,
        p_rmax: float | None = None,
        elec_name: str | None = None,
        elec_select: dict[str, list[float | None]] | None = None,
        ion_name: str | None = None,
        ion_select: dict[str, list[float | None]] | None = None,
        filename: str | Path,
        density_name: str,
        neutral: bool = True,
        lineout_axis: str | dict[str, dict[str, float]],
        centroid_axis: str | None = None,
        density_scale: float = 1.0,
        interpolation_points: dict[str, float] = ...,
        longitudinal_offset: float = 0.0,
        density_cutoff_ratio: float = 0.001,
        centering_mode: Literal['centroid', 'left', 'right'] = 'left',
    ) -> None:
        """Longitudinal density profile interpolated from an HDF5 density dataset.

        File structure:
            The HDF5 file must contain a root-level N-dimensional density dataset named
            by ``density_name``, with finite values. Its ``DIMENSION_LABELS`` attribute
            must contain one unique label per dimension in dataset-shape order. For each
            label, the file must contain a root-level one-dimensional coordinate dataset
            with at least two values, the same length as its corresponding density
            dimension, and finite, strictly increasing values. Density values must be
            finite and non-negative.

            ``lineout_axis`` can select one coordinate varied to create the longitudinal
            lineout, or define a parameterized linear path through multiple coordinates.
            In the path form, each coordinate follows
            ``coordinate(t) = origin + coefficient * t``.
            ``interpolation_points`` must provide exactly one in-bounds position for every
            labeled coordinate not included in the lineout. The selected lineout is
            normalized to its positive peak, which becomes ``nominal_density``; values
            outside the lineout coordinate range evaluate to zero.

            For example, ``my_profile.h5`` contains a root-level ``density`` dataset
            with ``DIMENSION_LABELS = ["z_m", "x_mm", "pressure_bar"]`` and coordinate
            datasets named ``z_m``, ``x_mm``, and ``pressure_bar``. A lineout can use
            ``lineout_axis="z_m"`` with
            ``interpolation_points={"x_mm": 2.0, "pressure_bar": 1.0}``, or an oblique
            ``x_mm``-``z_m`` line with
            ``lineout_axis={"z_m": {"origin": 0.0, "coefficient": 1 / sqrt(2)},
            "x_mm": {"origin": 2.0, "coefficient": 1.0e-3 / sqrt(2)}}`` and
            ``interpolation_points={"pressure_bar": 1.0}``. The user is responsible for
            choosing coefficients with compatible units.

        Args:
            p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
            p_nr: (int) Number of macroparticles per gridcell along the radial direction.
            p_nt: (int) Number of macroparticles per gridcell along the angular direction.
            species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
                If None, the plasma is assumed to be fully ionized and no ionization is considered.
                If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
                Defaults to Hydrogen.
            ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
                Defaults to unionized (ionization level 0).
            p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
            elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
            elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
                Defaults to None.
            ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
            ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Defaults to None.
            filename: (str | Path) Path to the HDF5 file. Config-file serialization
                records it relative to the config file, including ``..`` segments,
                so a config and its referenced data can be relocated together.
            density_name: (str) Name of the multidimensional density dataset.
            neutral: (bool) |OPTIONAL| Whether the data is of the neutral atomic density or of the ionized electron density. Defaults to True.
            lineout_axis: (str | dict[str, dict[str, float]]) Coordinate dataset varied to form the longitudinal lineout, or parameterized linear path definitions. In the dictionary form, every key is a coordinate dataset and its value must contain finite ``origin`` and ``coefficient`` values defining ``coordinate(t) = origin + coefficient * t``. At least one coefficient must be nonzero; zero coefficients keep their coordinate fixed at its origin. The returned density function uses the sampled ``t`` coordinate after applying ``centering_mode`` and ``longitudinal_offset``.
            centroid_axis: (str | None) |OPTIONAL| Coordinate dataset used to calculate the density-weighted centroid for ``centering_mode="centroid"``. If provided, this axis is varied while other parameterized-linear-path axes are fixed at their origins and remaining axes are fixed by ``interpolation_points``. It must be included in ``lineout_axis`` with a nonzero coefficient so its centroid can be converted to the lineout parameter. Defaults to None, which uses the selected lineout.
            density_scale: (float) |OPTIONAL| Scalar multiple to apply to the density. Defaults to 1.0.
            interpolation_points: (dict[str, float]) |OPTIONAL| Positions for every other coordinate axis. Defaults to {}.
            longitudinal_offset: (float) [m] |OPTIONAL| Offset applied to the lineout coordinates. Defaults to 0.0.
            density_cutoff_ratio: (float) |OPTIONAL| Relative-to-peak cutoff used to determine the longitudinal extent. Defaults to 1e-3.
            centering_mode: (Literal[str]) |OPTIONAL| Density centering method.
                If `'centroid'`, the density-weighted centroid will be located at `z=longitudinal_offset`.
                If `'left'`, the cutoff-derived left extent will be located at `z=longitudinal_offset`.
                If `'right'`, the cutoff-derived right extent will be located at `z=longitudinal_offset`.
                Defaults to `'left'`.
            nominal_density: (float) [m^-3] |NOT REFERENCED| The peak density for this profile. This quantity is determined by the dataset used."""
    def get_z_extent(self) -> tuple[float, float]:
        ...
    def get_r_extent(self) -> float | None:
        ...
    def build_density_function(self) -> DensityCallable:
        ...
