"""Generate `htu_synoptic_lpa.bob`: the HTU twin's synoptic with the LPA bunch tied in.

The twin's own `htu_synoptic.bob` is generated by that project and is not modified here. This
script reads it and writes a copy, next to `lpa_bunch.bob`, with three changes:

- a new bottom row shows the LPA bunch the twin is tracking (energy, energy spread, charge,
  macroparticles, read from the `Source_*` PVs), a combo box that selects the LPA run (the
  `LPA_Archive` PV, one option per archive `lume-fbpic-serve` was given) and a button that opens
  `lpa_bunch.bob`;
- the `SRC` element's button opens `lpa_bunch.bob` instead of the twin's source display. It is a
  single action on purpose: Phoebus draws a button with several actions as a drop-down menu, and a
  click on the small `SRC` element would then only open the menu. The LPA display shows every
  `Source_*` value the twin's source display does, and the `Source_*` PVs are read-only now;
- every `rotation_step` is converted from degrees to the ordinal Phoebus expects. The twin's
  generator writes `90.0` (an angle) for its vertical labels, but the property is an enum
  (0 = none, 1 = 90 degrees, 2 = 180, 3 = 270) and Phoebus logs a warning for each label and does not
  rotate it;
- every other display file the synoptic refers to -- the `open_display` buttons (`quad_controls.bob`,
  ...) and the camera tabs embedded in it (`camera_view.bob`) -- is pointed at the twin's display
  directory through a `TWIN_DISPLAYS` macro, so they keep working from here.

`TWIN_DISPLAYS` defaults to the directory the copy was built from; set it when opening the display
(`phoebus -resource htu_synoptic_lpa.bob?TWIN_DISPLAYS=/path/to/geecs-lume-twin/display`) if the
twin lives elsewhere. The PVs are the synoptic's own, `pva://HTU:SIM:...`.

Run `python generate_linked_synoptic.py <twin display dir> [output.bob]` again whenever the twin's
synoptic changes; do not edit the copy by hand. The twin's `display` directory is the one that
holds `htu_synoptic.bob`.
"""

from __future__ import annotations

import sys
import xml.etree.ElementTree as ET
from pathlib import Path

# Phoebus's `rotation_step` enum, by ordinal: 0 none, 1 = 90 degrees, 2 = 180, 3 = 270.
ROTATION_ORDINAL = {0.0: 0, 90.0: 1, 180.0: 2, 270.0: 3, -90.0: 3}

STRIP_HEIGHT = 44
LPA_DISPLAY = "lpa_bunch.bob"
SELECTOR = "LPA_Archive"  # the enum PV `lume-fbpic-serve` serves, one option per archive
PREFIX = "pva://HTU:SIM:"

# (label, PV name, label width, value width, decimals)
STRIP = (
    ("Energy [MeV]", "Source_Energy_MeV", 90, 70, 2),
    ("Spread [%]", "Source_EnergySpread_pct", 80, 60, 1),
    ("Charge [pC]", "Source_Charge_pC", 85, 70, 1),
    ("Macroparticles", "Source_NumParticles", 100, 70, 0),
)


def _text(parent: ET.Element, tag: str, text: str) -> ET.Element:
    child = ET.SubElement(parent, tag)
    child.text = text
    return child


def _geometry(widget: ET.Element, x: int, y: int, w: int, h: int) -> None:
    for tag, value in (("x", x), ("y", y), ("width", w), ("height", h)):
        _text(widget, tag, str(value))


def _label(root, name, text, x, y, w, h=24, bold=False):
    widget = ET.SubElement(root, "widget", type="label", version="2.0.0")
    _text(widget, "name", name)
    _text(widget, "text", text)
    _geometry(widget, x, y, w, h)
    if bold:
        font = ET.SubElement(ET.SubElement(widget, "font"), "font")
        font.set("family", "Liberation Sans")
        font.set("style", "BOLD")
        font.set("size", "12.0")


def _value(root, name, pv, x, y, w, h, decimals):
    widget = ET.SubElement(root, "widget", type="textupdate", version="2.0.0")
    _text(widget, "name", name)
    _text(widget, "pv_name", PREFIX + pv)
    _geometry(widget, x, y, w, h)
    _text(widget, "precision", str(decimals))
    _text(widget, "precision_from_pv", "false")
    _text(widget, "show_units", "false")


def _combo(root, name, pv, x, y, w, h):
    widget = ET.SubElement(root, "widget", type="combo", version="2.0.0")
    _text(widget, "name", name)
    _text(widget, "pv_name", PREFIX + pv)
    _geometry(widget, x, y, w, h)
    _text(widget, "items_from_pv", "true")


def _lpa_action(parent: ET.Element) -> None:
    action = ET.SubElement(parent, "action", type="open_display")
    _text(action, "file", LPA_DISPLAY)
    ET.SubElement(action, "macros")
    _text(action, "target", "window")
    _text(action, "description", "LPA bunch: the twin's source readbacks and the moment descriptor")


def build(twin_display_dir: Path) -> str:
    """The linked synoptic's XML, built from `<twin_display_dir>/htu_synoptic.bob`."""
    source = twin_display_dir / "htu_synoptic.bob"
    root = ET.parse(source).getroot()

    macros = ET.Element("macros")
    _text(macros, "TWIN_DISPLAYS", str(twin_display_dir.resolve()))
    root.insert(1, macros)

    for step in root.iter("rotation_step"):
        angle = float(step.text)
        if angle not in ROTATION_ORDINAL:
            raise ValueError(f"rotation_step {step.text!r} is not a multiple of 90 degrees")
        step.text = str(ROTATION_ORDINAL[angle])

    # Every <file>, whatever holds it: button actions, and the tabs that embed the camera views.
    for file in root.iter("file"):
        if file.text and not file.text.startswith("$("):
            file.text = f"$(TWIN_DISPLAYS)/{file.text}"

    src_buttons = [
        w
        for w in root.findall("widget")
        if w.get("type") == "action_button" and (w.findtext("name") or "").startswith("btn_SRC")
    ]
    if len(src_buttons) != 1:
        raise ValueError(f"expected one SRC button in {source}, found {len(src_buttons)}")
    actions = src_buttons[0].find("actions")
    for action in list(actions):
        actions.remove(action)
    _lpa_action(actions)
    tooltip = src_buttons[0].find("tooltip")
    if tooltip is not None:
        tooltip.text = "LPA bunch: the twin's source readbacks and the moment descriptor"

    height = int(root.findtext("height"))
    root.find("height").text = str(height + STRIP_HEIGHT)
    y = height + 8

    rule = ET.SubElement(root, "widget", type="rectangle", version="2.0.0")
    _text(rule, "name", "lpa_strip_rule")
    _geometry(rule, 30, height + 2, 1440, 1)
    _text(rule, "line_width", "0")
    background = ET.SubElement(rule, "background_color")
    ET.SubElement(background, "color", red="150", green="150", blue="150", alpha="255")

    x = 30
    _label(root, "lpa_strip_title", "LPA bunch (twin source):", x, y, 190, bold=True)
    x += 195
    _label(root, "lpa_strip_run_label", "Run:", x, y, 40)
    _combo(root, "lpa_strip_run", SELECTOR, x + 42, y, 170, 24)
    x += 42 + 170 + 16
    for index, (text, pv, label_w, value_w, decimals) in enumerate(STRIP):
        _label(root, f"lpa_strip_label{index}", text, x, y, label_w)
        _value(root, f"lpa_strip_value{index}", pv, x + label_w, y, value_w, 24, decimals)
        x += label_w + value_w + 14

    button = ET.SubElement(root, "widget", type="action_button", version="3.0.0")
    _text(button, "name", "lpa_strip_button")
    _lpa_action(ET.SubElement(button, "actions"))
    _text(button, "text", "LPA bunch...")
    _geometry(button, x, y - 1, 130, 26)

    ET.indent(root, space="  ")
    return '<?xml version="1.0" encoding="UTF-8"?>\n' + ET.tostring(root, encoding="unicode") + "\n"


def main(argv: list[str] | None = None) -> None:
    argv = sys.argv[1:] if argv is None else argv
    if not argv:
        sys.exit(f"usage: python {Path(__file__).name} <twin display dir> [output.bob]")
    output = Path(argv[1]) if len(argv) > 1 else Path(__file__).with_name("htu_synoptic_lpa.bob")
    output.write_text(build(Path(argv[0])))
    print(f"wrote {output}")


if __name__ == "__main__":
    main()
