"""Render ``.pyi`` stub source from a :class:`~.index.LibIndex`.

Each generated stub file contains class definitions with MRO-merged
docstrings and explicit ``__init__`` signatures so that Pyright / Pylance
surfaces complete parameter documentation in Cursor's hover tooltips.
"""

from __future__ import annotations

import ast
import inspect
import textwrap
from pathlib import Path

from .index import (
    ClassKey,
    InitField,
    LibIndex,
    ParsedClass,
    ParsedField,
    ParsedMethod,
    default_lib_dir,
)

_GENERATED_HEADER = (
    "# Auto-generated by tools/sync_config_docstrings.py — do not edit by hand.\n"
)


def _quote_docstring(text: str) -> str:
    """Wrap *text* in triple-quoted string syntax for use in a stub."""
    if not text:
        return '""" """'
    escaped = text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    return f'"""{escaped}"""'


def _render_docstring(text: str, indent: str) -> str:
    """Quote and indent a generated docstring to its surrounding scope."""
    return textwrap.indent(_quote_docstring(inspect.cleandoc(text)), indent)


def _param_signature(field: InitField) -> str:
    """Format a single keyword-only parameter for an ``__init__`` stub."""
    if field.default is None:
        return f"{field.name}: {field.annotation}"
    return f"{field.name}: {field.annotation} = {field.default}"


def _expression_names(expression: str) -> set[str]:
    """Return names referenced by a valid expression, or an empty set."""
    try:
        tree = ast.parse(expression, mode="eval")
    except SyntaxError:
        return set()
    return {node.id for node in ast.walk(tree) if isinstance(node, ast.Name)}


def _annotation_names(node: ast.AST) -> set[str]:
    """Return names in an annotation, including postponed string annotations."""
    names = {child.id for child in ast.walk(node) if isinstance(child, ast.Name)}
    for child in ast.walk(node):
        if isinstance(child, ast.Constant) and isinstance(child.value, str):
            names.update(_expression_names(child.value))
    return names


def _annotation_text_names(annotation: str) -> set[str]:
    """Return names from source text representing an annotation."""
    try:
        tree = ast.parse(annotation, mode="eval")
    except SyntaxError:
        return set()
    return _annotation_names(tree)


def _parameter_names(params: str) -> set[str]:
    """Return names referenced by annotations and defaults in *params*."""
    if not params:
        return set()
    try:
        function = ast.parse(f"def stub({params}): pass").body[0]
    except SyntaxError:
        return set()
    assert isinstance(function, ast.FunctionDef)
    expressions = [
        annotation
        for argument in (
            *function.args.posonlyargs,
            *function.args.args,
            *function.args.kwonlyargs,
        )
        if (annotation := argument.annotation) is not None
    ]
    if function.args.vararg and function.args.vararg.annotation:
        expressions.append(function.args.vararg.annotation)
    if function.args.kwarg and function.args.kwarg.annotation:
        expressions.append(function.args.kwarg.annotation)
    expressions.extend(
        default
        for default in (*function.args.defaults, *function.args.kw_defaults)
        if default
    )
    names = {
        name for expression in expressions for name in _annotation_names(expression)
    }
    for default in (*function.args.defaults, *function.args.kw_defaults):
        if default:
            names.update(
                node.id for node in ast.walk(default) if isinstance(node, ast.Name)
            )
    return names


def _signature_names(
    fields: list[InitField],
    methods: list[ParsedMethod],
    class_fields: list[ParsedField],
) -> set[str]:
    """Collect names referenced by generated fields, parameters, and returns."""
    names = {
        name
        for field in (*fields, *class_fields)
        for name in _annotation_text_names(field.annotation)
    }
    names.update(
        name
        for field in fields
        if field.default
        for name in _expression_names(field.default)
    )
    for m in methods:
        names.update(_parameter_names(m.params))
        if m.return_annotation:
            names.update(_annotation_text_names(m.return_annotation))
    if any("abstractmethod" in method.decorators for method in methods):
        names.add("abstractmethod")
    return names


def _relative_module_import(module: str, source_module: str, name: str) -> str:
    """Render an import of *name* relative to the generated *module*."""
    package_parts = module.split(".")[:-1]
    source_parts = source_module.split(".")
    common_parts = 0
    while (
        common_parts < len(package_parts)
        and common_parts < len(source_parts)
        and package_parts[common_parts] == source_parts[common_parts]
    ):
        common_parts += 1
    prefix = "." * (len(package_parts) - common_parts + 1)
    target = ".".join(source_parts[common_parts:])
    return f"from {prefix}{target} import {name}"


def _public_config_reexports(index: LibIndex, module: str) -> list[str]:
    """Return explicit re-exports for public imported config classes."""
    return sorted(
        f"{_relative_module_import(module, source_module, name)} as {name}"
        for name, source_module in index.imports.get(module, {}).items()
        if (
            not name.startswith("_")
            and source_module != module
            and "." in source_module
            and (source_module, name) in index.classes
        )
    )


def _stub_dependencies(
    index: LibIndex,
    module: str,
    classes: list[ParsedClass],
    fields: list[InitField],
    methods: list[ParsedMethod],
    class_fields: list[ParsedField],
) -> tuple[list[str], list[str]]:
    """Return imports and aliases required by names used in generated signatures."""
    pending = _signature_names(fields, methods, class_fields)
    local_classes = {parsed.name for parsed in classes}
    imports: set[str] = set()
    definitions: set[str] = set()
    import_map = index.imports.get(module, {})
    import_lines = (index.import_lines or {}).get(module, {})
    module_definitions = (index.definitions or {}).get(module, {})

    while pending:
        name = pending.pop()
        if name in local_classes:
            continue
        if definition := module_definitions.get(name):
            if definition not in definitions:
                definitions.add(definition)
                pending.update(_expression_names(definition))
            continue
        source_module = import_map.get(name)
        if source_module is None:
            continue
        if (source_module, name) in index.classes:
            if source_module != module:
                imports.add(_relative_module_import(module, source_module, name))
            continue
        if import_line := import_lines.get(name):
            imports.add(import_line)

    return sorted(imports), sorted(definitions)


def _render_init_method(index: LibIndex, parsed: ParsedClass) -> str:
    """Return an ``__init__`` stub with keyword-only params and merged docs.

    Returns an empty string when *parsed* has no init fields.
    """
    fields = index.init_fields(parsed)
    if not fields:
        return ""
    params = ",\n        ".join(_param_signature(field) for field in fields)
    docstring = _render_docstring(index.merged_docstring(parsed), "        ")
    return (
        "    def __init__(\n"
        "        self,\n"
        "        *,\n"
        f"        {params},\n"
        "    ) -> None:\n"
        f"{docstring}\n"
    )


def _render_method(method: ParsedMethod) -> str:
    """Render a single public method stub."""
    lines: list[str] = []
    for dec in method.decorators:
        lines.append(f"    @{dec}")

    is_property = "property" in method.decorators
    is_classmethod = "classmethod" in method.decorators
    is_static = "staticmethod" in method.decorators

    if is_property:
        first_param = "self"
        params_str = ""
    elif is_classmethod:
        first_param = "cls"
        params_str = f", {method.params}" if method.params else ""
    elif is_static:
        first_param = ""
        params_str = method.params
    else:
        first_param = "self"
        params_str = f", {method.params}" if method.params else ""

    ret = f" -> {method.return_annotation}" if method.return_annotation else ""

    if is_static:
        sig = f"    def {method.name}({params_str}){ret}:"
    elif is_property:
        sig = f"    def {method.name}({first_param}){ret}:"
    else:
        sig = f"    def {method.name}({first_param}{params_str}){ret}:"

    lines.append(sig)
    if method.docstring:
        lines.append(_render_docstring(method.docstring, "        "))
    lines.append("        ...")
    return "\n".join(lines)


def _collect_external_imports(
    index: LibIndex, module: str, classes: list[ParsedClass]
) -> list[ClassKey]:
    """Return sorted cross-module base-class keys needed as stub imports."""
    return sorted(
        {
            resolved_key
            for parsed in classes
            for _base_name, resolved_key in index.resolved_bases(parsed)
            if resolved_key[0] != module
        }
    )


def _render_class_block(index: LibIndex, parsed: ParsedClass) -> str:
    """Render a single class definition (header + fields + ``__init__`` + methods)."""
    bases = [name for name, _key in index.resolved_bases(parsed)]
    header = f"class {parsed.name}"
    if bases:
        header += f"({', '.join(bases)})"
    block_lines = [
        f"{header}:",
        _render_docstring(index.merged_docstring(parsed), "    "),
    ]
    for field in parsed.fields:
        block_lines.append(f"    {field.name}: {field.annotation}")
    init_stub = _render_init_method(index, parsed)
    if init_stub:
        block_lines.append(init_stub.rstrip())
    for method in parsed.methods:
        block_lines.append(_render_method(method))
    return "\n".join(block_lines)


def generate_module_pyi(
    module: str,
    *,
    lib_dir: Path | None = None,
    index: LibIndex | None = None,
) -> str:
    """Return complete ``.pyi`` stub source for config classes in *module*.

    Args:
        module: Module stem (e.g. ``"density"``).
        lib_dir: Directory containing the source ``.py`` files.  Defaults to
            :func:`~.index.default_lib_dir`.
        index: Pre-built :class:`~.index.LibIndex`.  One is created from
            *lib_dir* when ``None``.

    Returns:
        Full stub file content as a string, or ``""`` when *module* contains
        no config classes.
    """
    lib_dir = lib_dir or default_lib_dir()
    index = index or LibIndex.from_lib_dir(lib_dir)
    classes = index.classes_in_module(module)
    if not classes:
        return ""

    external = _collect_external_imports(index, module, classes)
    all_fields = [f for parsed in classes for f in index.init_fields(parsed)]
    all_methods = [m for parsed in classes for m in parsed.methods]
    all_class_fields = [f for parsed in classes for f in parsed.fields]
    stub_imports, stub_definitions = _stub_dependencies(
        index,
        module,
        classes,
        all_fields,
        all_methods,
        all_class_fields,
    )
    external = [
        (base_module, base_name)
        for base_module, base_name in external
        if _relative_module_import(module, base_module, base_name) not in stub_imports
    ]

    lines = [_GENERATED_HEADER.rstrip(), "", "from __future__ import annotations", ""]
    for base_module, base_name in external:
        lines.append(_relative_module_import(module, base_module, base_name))
    if external:
        lines.append("")

    for import_line in stub_imports:
        lines.append(import_line)
    if stub_imports:
        lines.append("")
    reexports = _public_config_reexports(index, module)
    lines.extend(reexports)
    if reexports:
        lines.append("")
    for definition in stub_definitions:
        lines.append(definition)
    if stub_definitions:
        lines.append("")

    body = "\n\n".join(_render_class_block(index, parsed) for parsed in classes) + "\n"
    lines.append(body.rstrip() + "\n")
    return "\n".join(lines)
