# Auto-generated by tools/sync_config_docstrings.py — do not edit by hand.

from __future__ import annotations

from ..laser import _LaserPulse

from fbpic.lpa_utils.laser.laser_profiles import LaserProfile
from pathlib import Path
from typing import Any, ClassVar, Literal, TYPE_CHECKING
import matplotlib.pyplot as plt

class LasyLaserPulse(_LaserPulse):
    """Super-Gaussian laser pulse with Zernike and spectral-phase aberrations, built with LASY.

    Thin wrapper around ``inversion_fbpic.utils.laser.HighOrderLasyLaser``: every
    field below maps onto one of its physical parameters or hyperparameters and
    carries the same default. The pulse is constructed at focus, back-propagated
    to the simulation start plane, optionally re-centred, normalized to
    ``energy``, and written to a LASY HDF5 file that FBPIC reads through
    ``FromLasyFileLaser``. The build is expensive and happens once, in
    ``prepare()``, on MPI rank 0 only; the other ranks block in a broadcast and
    receive either the file path or rank 0's error, so a bad configuration
    fails on every rank instead of hanging. Physical validation (grid/mode consistency, spectral-phase
    requirements, pulse-duration limits) is performed by ``HighOrderLasyLaser``
    at build time.

    Only ``energy`` may be provided. ``a0`` is measured numerically from the
    field at focus during ``prepare()`` and is reported as ``out_a0``
    (``null`` in YAML written before the build).

    LASY pulses can only be emitted through an antenna, so ``method`` is fixed
    to ``"antenna"``, ``v_antenna`` to ``0.0``, and ``z0_antenna`` is required.
    FBPIC resets the LASY time axis to zero, so the peak intensity leaves the
    antenna at ``t_start`` plus the peak's delay from the start of the LASY time
    window: ``3 * tau_fwhm`` for the default transform-limited pulse, or exactly
    ``peak_delay_from_file_start`` when that is set. ``z0`` is informational
    only (nominal centroid at ``t = 0``, used for plotting extents); for a
    consistent picture set ``z0 = z0_antenna - c * (t_start + peak_delay)``.

    Args:
        energy: (float) [J] Energy of the laser pulse in Joules. Required: the LASY field is normalized to this energy and `a0` is measured from it.
        a0: (None) Not accepted. The normalized amplitude is measured numerically at focus during `prepare()` and reported as `out_a0` (`null` before the build).
        z0: (float) [m] Nominal centroid position at t = 0 in meters, used only for plotting extents. Emission timing is set by `z0_antenna`, `t_start`, and `peak_delay_from_file_start`; for a consistent picture use `z0 = z0_antenna - c * (t_start + peak_delay)`.
        method: (Literal["antenna"]|None) |OPTIONAL| Fixed to "antenna": LASY files can only be emitted by FBPIC's laser antenna. None means "antenna"; "direct" is rejected.
        z0_antenna: (float) [m] Position of the stationary antenna that emits the pulse, in meters. Required.
        v_antenna: (float|None) [m/s] |OPTIONAL| Must be 0 or None (stored as 0.0): a LASY pulse cannot be emitted from a moving antenna.
        wavelength: (float) [m] Central wavelength of the laser pulse in meters.
        tau_fwhm: (float) [s] Full-width at half-maximum intensity duration of the transform-limited pulse in seconds.
        waist: (float) [m] Super-Gaussian spot size (1/e^2 radius for order 2) at focus in meters.
        focal_position: (float) [m] Focal position of the laser pulse in meters, relative to the simulation start plane.
        super_gaussian_order: (float) Super-Gaussian order of the transverse profile. 2.0 is Gaussian.
        zernike_coefficients: (dict[str, float]) [rad] |OPTIONAL| Zernike phase amplitudes at focus keyed by name (astigmatism_2, astigmatism_4, coma_y, coma_x, trefoil_y, trefoil_x, spherical_3, astigmatism_6, coma_5_y, coma_5_x, secondary_trefoil_y, secondary_trefoil_x). Missing names default to 0.0; unknown names are rejected.
        spectral_bandwidth: (float|Literal["auto"]|None) [rad/s] |OPTIONAL| Gaussian spectral-intensity FWHM in angular frequency. `"auto"` derives the transform-limited value from `tau_fwhm`; None (default) keeps `HighOrderLasyLaser`'s default of 0, i.e. an analytic Gaussian envelope without spectral phase.
        cep: (float|None) [rad] |OPTIONAL| Carrier-envelope phase. None (default) keeps `HighOrderLasyLaser`'s default of 0.
        gdd: (float|None) [s^2] |OPTIONAL| Group-delay dispersion about the central frequency. Requires a nonzero `spectral_bandwidth`. None (default) applies none; mutually exclusive with `gdd_relative`.
        tod: (float|None) [s^3] |OPTIONAL| Third-order spectral phase. Requires a nonzero `spectral_bandwidth`. None (default) applies none; mutually exclusive with `tod_relative`.
        fod: (float|None) [s^4] |OPTIONAL| Fourth-order spectral phase. Requires a nonzero `spectral_bandwidth`. None (default) applies none.
        gdd_relative: (float|None) |OPTIONAL| Duration-normalized GDD in [-1, 1]; +1 corresponds to 5e-28 s^2 at 30 fs FWHM and scales with duration squared. None (default) applies none.
        tod_relative: (float|None) |OPTIONAL| Duration-normalized TOD in [-1, 1]; +1 corresponds to 1e-41 s^3 at 30 fs FWHM and scales with duration cubed. None (default) applies none.
        polarization: (tuple[float, float]) |OPTIONAL| Real Jones vector (Ex, Ey) passed to LASY. Defaults to (1, 0), linear along x.
        n_azimuthal_modes: (int) |OPTIONAL| Number of azimuthal modes in the LASY r-t grid. Defaults to 5.
        num_points: (tuple[int, int]) |OPTIONAL| LASY grid points (radial, temporal). Defaults to (600, 900).
        hi_range: (float) [waists] |OPTIONAL| Radial extent of the LASY grid in units of `waist`. Defaults to 8.0.
        center_and_remove_tilt: (bool) |OPTIONAL| Re-centre the fluence and remove the mean transverse phase gradient at the start plane. Defaults to True.
        centering_angles: (int) |OPTIONAL| Number of polar angles used for centering; must be at least 2 * n_azimuthal_modes - 1. Defaults to 72.
        spectral_time_window_factor: (float) |OPTIONAL| Temporal half-width of the LASY grid in units of the transform-limited half-duration when `spectral_bandwidth` is nonzero. Defaults to 6.0.
        peak_delay_from_file_start: (float|None) [s] |OPTIONAL| Place the on-axis intensity peak at this delay after the start of the LASY time window (the delay FBPIC uses for emission). None (default) leaves the peak at the window centre.
        maximum_pulse_duration_fwhm: (float|None) [s] |OPTIONAL| Reject the build if the start-plane on-axis FWHM exceeds this duration. None (default) disables the check.
        lasy_file: (Path|str) |OPTIONAL| Output prefix for the LASY HDF5 file; the written file is `<parent>/<stem>_00000.h5`. If not absolute, this is relative to the `working_directory` passed to `Simulation.setup_simulation()` (or to `prepare(relative_to=...)`), falling back to the current working directory. Defaults to `diags/lasy_laser`.
        t_start: (float) [s] |OPTIONAL| Delay before the antenna starts emitting the LASY file, as in FBPIC's `FromLasyFileLaser`. Defaults to 0.0."""
    SUBCLASS: ClassVar[str]
    wavelength: float
    tau_fwhm: float
    waist: float
    focal_position: float
    super_gaussian_order: float
    zernike_coefficients: dict[str, float]
    spectral_bandwidth: float | Literal['auto'] | None
    cep: float | None
    gdd: float | None
    tod: float | None
    fod: float | None
    gdd_relative: float | None
    tod_relative: float | None
    polarization: tuple[float, float]
    n_azimuthal_modes: int
    num_points: tuple[int, int]
    hi_range: float
    center_and_remove_tilt: bool
    centering_angles: int
    spectral_time_window_factor: float
    peak_delay_from_file_start: float | None
    maximum_pulse_duration_fwhm: float | None
    lasy_file: Path
    t_start: float
    lasy_file_path: Path | None
    def __init__(
        self,
        *,
        energy: float | None = None,
        a0: float | None = None,
        z0: float,
        method: Literal['direct', 'antenna'] | None = None,
        z0_antenna: float | None = None,
        v_antenna: float | None = None,
        wavelength: float,
        tau_fwhm: float,
        waist: float,
        focal_position: float,
        super_gaussian_order: float,
        zernike_coefficients: dict[str, float] = None,
        spectral_bandwidth: float | Literal['auto'] | None = None,
        cep: float | None = None,
        gdd: float | None = None,
        tod: float | None = None,
        fod: float | None = None,
        gdd_relative: float | None = None,
        tod_relative: float | None = None,
        polarization: tuple[float, float] = (1.0, 0.0),
        n_azimuthal_modes: int = 5,
        num_points: tuple[int, int] = (600, 900),
        hi_range: float = 8.0,
        center_and_remove_tilt: bool = True,
        centering_angles: int = 72,
        spectral_time_window_factor: float = 6.0,
        peak_delay_from_file_start: float | None = None,
        maximum_pulse_duration_fwhm: float | None = None,
        lasy_file: Path = Path('diags/lasy_laser'),
        t_start: float = 0.0,
    ) -> None:
        """Super-Gaussian laser pulse with Zernike and spectral-phase aberrations, built with LASY.

        Thin wrapper around ``inversion_fbpic.utils.laser.HighOrderLasyLaser``: every
        field below maps onto one of its physical parameters or hyperparameters and
        carries the same default. The pulse is constructed at focus, back-propagated
        to the simulation start plane, optionally re-centred, normalized to
        ``energy``, and written to a LASY HDF5 file that FBPIC reads through
        ``FromLasyFileLaser``. The build is expensive and happens once, in
        ``prepare()``, on MPI rank 0 only; the other ranks block in a broadcast and
        receive either the file path or rank 0's error, so a bad configuration
        fails on every rank instead of hanging. Physical validation (grid/mode consistency, spectral-phase
        requirements, pulse-duration limits) is performed by ``HighOrderLasyLaser``
        at build time.

        Only ``energy`` may be provided. ``a0`` is measured numerically from the
        field at focus during ``prepare()`` and is reported as ``out_a0``
        (``null`` in YAML written before the build).

        LASY pulses can only be emitted through an antenna, so ``method`` is fixed
        to ``"antenna"``, ``v_antenna`` to ``0.0``, and ``z0_antenna`` is required.
        FBPIC resets the LASY time axis to zero, so the peak intensity leaves the
        antenna at ``t_start`` plus the peak's delay from the start of the LASY time
        window: ``3 * tau_fwhm`` for the default transform-limited pulse, or exactly
        ``peak_delay_from_file_start`` when that is set. ``z0`` is informational
        only (nominal centroid at ``t = 0``, used for plotting extents); for a
        consistent picture set ``z0 = z0_antenna - c * (t_start + peak_delay)``.

        Args:
            energy: (float) [J] Energy of the laser pulse in Joules. Required: the LASY field is normalized to this energy and `a0` is measured from it.
            a0: (None) Not accepted. The normalized amplitude is measured numerically at focus during `prepare()` and reported as `out_a0` (`null` before the build).
            z0: (float) [m] Nominal centroid position at t = 0 in meters, used only for plotting extents. Emission timing is set by `z0_antenna`, `t_start`, and `peak_delay_from_file_start`; for a consistent picture use `z0 = z0_antenna - c * (t_start + peak_delay)`.
            method: (Literal["antenna"]|None) |OPTIONAL| Fixed to "antenna": LASY files can only be emitted by FBPIC's laser antenna. None means "antenna"; "direct" is rejected.
            z0_antenna: (float) [m] Position of the stationary antenna that emits the pulse, in meters. Required.
            v_antenna: (float|None) [m/s] |OPTIONAL| Must be 0 or None (stored as 0.0): a LASY pulse cannot be emitted from a moving antenna.
            wavelength: (float) [m] Central wavelength of the laser pulse in meters.
            tau_fwhm: (float) [s] Full-width at half-maximum intensity duration of the transform-limited pulse in seconds.
            waist: (float) [m] Super-Gaussian spot size (1/e^2 radius for order 2) at focus in meters.
            focal_position: (float) [m] Focal position of the laser pulse in meters, relative to the simulation start plane.
            super_gaussian_order: (float) Super-Gaussian order of the transverse profile. 2.0 is Gaussian.
            zernike_coefficients: (dict[str, float]) [rad] |OPTIONAL| Zernike phase amplitudes at focus keyed by name (astigmatism_2, astigmatism_4, coma_y, coma_x, trefoil_y, trefoil_x, spherical_3, astigmatism_6, coma_5_y, coma_5_x, secondary_trefoil_y, secondary_trefoil_x). Missing names default to 0.0; unknown names are rejected.
            spectral_bandwidth: (float|Literal["auto"]|None) [rad/s] |OPTIONAL| Gaussian spectral-intensity FWHM in angular frequency. `"auto"` derives the transform-limited value from `tau_fwhm`; None (default) keeps `HighOrderLasyLaser`'s default of 0, i.e. an analytic Gaussian envelope without spectral phase.
            cep: (float|None) [rad] |OPTIONAL| Carrier-envelope phase. None (default) keeps `HighOrderLasyLaser`'s default of 0.
            gdd: (float|None) [s^2] |OPTIONAL| Group-delay dispersion about the central frequency. Requires a nonzero `spectral_bandwidth`. None (default) applies none; mutually exclusive with `gdd_relative`.
            tod: (float|None) [s^3] |OPTIONAL| Third-order spectral phase. Requires a nonzero `spectral_bandwidth`. None (default) applies none; mutually exclusive with `tod_relative`.
            fod: (float|None) [s^4] |OPTIONAL| Fourth-order spectral phase. Requires a nonzero `spectral_bandwidth`. None (default) applies none.
            gdd_relative: (float|None) |OPTIONAL| Duration-normalized GDD in [-1, 1]; +1 corresponds to 5e-28 s^2 at 30 fs FWHM and scales with duration squared. None (default) applies none.
            tod_relative: (float|None) |OPTIONAL| Duration-normalized TOD in [-1, 1]; +1 corresponds to 1e-41 s^3 at 30 fs FWHM and scales with duration cubed. None (default) applies none.
            polarization: (tuple[float, float]) |OPTIONAL| Real Jones vector (Ex, Ey) passed to LASY. Defaults to (1, 0), linear along x.
            n_azimuthal_modes: (int) |OPTIONAL| Number of azimuthal modes in the LASY r-t grid. Defaults to 5.
            num_points: (tuple[int, int]) |OPTIONAL| LASY grid points (radial, temporal). Defaults to (600, 900).
            hi_range: (float) [waists] |OPTIONAL| Radial extent of the LASY grid in units of `waist`. Defaults to 8.0.
            center_and_remove_tilt: (bool) |OPTIONAL| Re-centre the fluence and remove the mean transverse phase gradient at the start plane. Defaults to True.
            centering_angles: (int) |OPTIONAL| Number of polar angles used for centering; must be at least 2 * n_azimuthal_modes - 1. Defaults to 72.
            spectral_time_window_factor: (float) |OPTIONAL| Temporal half-width of the LASY grid in units of the transform-limited half-duration when `spectral_bandwidth` is nonzero. Defaults to 6.0.
            peak_delay_from_file_start: (float|None) [s] |OPTIONAL| Place the on-axis intensity peak at this delay after the start of the LASY time window (the delay FBPIC uses for emission). None (default) leaves the peak at the window centre.
            maximum_pulse_duration_fwhm: (float|None) [s] |OPTIONAL| Reject the build if the start-plane on-axis FWHM exceeds this duration. None (default) disables the check.
            lasy_file: (Path|str) |OPTIONAL| Output prefix for the LASY HDF5 file; the written file is `<parent>/<stem>_00000.h5`. If not absolute, this is relative to the `working_directory` passed to `Simulation.setup_simulation()` (or to `prepare(relative_to=...)`), falling back to the current working directory. Defaults to `diags/lasy_laser`.
            t_start: (float) [s] |OPTIONAL| Delay before the antenna starts emitting the LASY file, as in FBPIC's `FromLasyFileLaser`. Defaults to 0.0."""
    @property
    def physical_parameters(self) -> dict[str, Any]:
        """``HighOrderLasyLaser`` physical parameters; unset optional fields are omitted."""
        ...
    @property
    def hyperparameters(self) -> dict[str, Any]:
        """``HighOrderLasyLaser`` hyperparameters built from this config."""
        ...
    @property
    def is_prepared(self) -> bool:
        """Whether ``prepare()`` has produced the LASY file."""
        ...
    def resolve_lasy_file(self, relative_to: Path | str | None=None) -> Path:
        """Absolute output prefix for the LASY file.

        A relative ``lasy_file`` is anchored at *relative_to* when given, otherwise
        at the current working directory."""
        ...
    def prepare(self, comm: Any | None=None, *, relative_to: Path | str | None=None) -> None:
        """Build the LASY pulse, write its HDF5 file, and measure a0 at focus.

        Runs the expensive build on rank 0 only. With MPI, the other ranks block
        in a broadcast until rank 0 has either written the file (they receive
        its path and a0) or failed (they receive the error and raise a
        ``RuntimeError`` naming it, while rank 0 re-raises the original
        exception). Calling this again after a successful build is a no-op.

        Args:
            comm: (BoundaryCommunicator|mpi4py.MPI.Comm|None) Communicator for the
                rank-0 build and result broadcast. Accepts FBPIC's ``sim.comm``, an mpi4py
                communicator such as ``MPI.COMM_WORLD``, or ``None`` when running
                without MPI (the calling process builds the file itself).
            relative_to: (Path|str|None) Directory a relative ``lasy_file`` is written
                under. ``Simulation`` passes its ``working_directory``; ``None`` means
                the current working directory."""
        ...
    def to_dict(self, *, include_nones: bool=True) -> dict[str, Any]:
        ...
    def resolve_laser_energy(self) -> float:
        ...
    def resolve_laser_a0(self) -> float:
        ...
    def build_laser_profile(self) -> LaserProfile | list[LaserProfile]:
        ...
    def get_r_extent(self, simulation_extent: tuple[float, float], num_sigma: float=3.0) -> float:
        """Get the radial extent of the laser pulse in meters. Assumes vacuum propagation.
        This uses a Gaussian approximation, and higher order modes can
        extend the radial extent of the pulse beyond this value. Use with caution.

        Args:
            simulation_extent: (tuple[float, float]) The extent of the full simulation in meters.
            num_sigma: (float) Number of sigmas to account for in the radial extent.

        Returns:
            float: The radial extent of the laser pulse in meters."""
        ...
    def plot(self, *, mode: Literal['lineout', 'lineout_and_2d']='lineout_and_2d', ax: 'plt.Axes | None'=None, num: int=600, output_path: Path | str | None=None, show: bool=False, label: str | None=None) -> 'plt.Figure':
        """Plot the start-plane LASY envelope and (optionally) a face-on |E| map.

        Delegates to ``utils.laser.plot_start_plane``. Needs the LASY ``Laser``
        object, so this only works on the rank that ran ``prepare()`` (it runs
        ``prepare()`` itself if needed).

        Args:
            mode: (Literal["lineout", "lineout_and_2d"]) Panel layout.
                ``"lineout"`` shows only the on-axis longitudinal envelope.
                ``"lineout_and_2d"`` (default) adds a face-on field-amplitude
                map at the start plane with a quiver overlay of the
                polarization field.
            ax: (matplotlib.axes.Axes|None) If provided, the longitudinal envelope
                is also drawn on this external axes (for combined overlay figures).
            num: (int) Number of points for the resampled longitudinal lineout.
            output_path: (Path|str|None) If given, the figure is saved here.
            show: (bool) Whether to call ``plt.show()``.
            label: (str|None) Label for the external *ax* lineout. Defaults to
                ``SUBCLASS (polarization)``.

        Returns:
            The created matplotlib Figure."""
        ...
