# Auto-generated by tools/sync_config_docstrings.py — do not edit by hand.

from __future__ import annotations

from .density_core import _DensityModifier
from .density_core import _DensityProfile
from inversion_fbpic.lib.density_core import _DensityProfile, _DensityModifier, DensityCallable
from pathlib import Path
from typing import ClassVar, List

class MatchedRadialModifier(_DensityModifier):
    """Add radial matched profile dependence to a z-dependent density function.

    The resulting function has the form:
    density(z, r) = n_p0(z) * (1 + r^2 / (pi * r_e * n_p0(z) * w_m^4))

    where:
    - n_p0(z) is the z-dependent density profile (z_density_func)
    - r_e is the classical electron radius
    - w_m is the matched spot size parameter, calculated using plasma density

    This radial profile represents a matched beam envelope condition where the
    radial modulation depends on the local plasma density.

    Args:
        matched_density: (float) [m^-3] Nominal plasma density in m^-3 used to scale the matched spot size parameter.
            This may be unique from the base density profile's nominal density.
        radial_extent: float | None [m] |OPTIONAL| Radial extent of the density profile. If None, the radial extent is determined by the simulation grid."""
    SUBCLASS: ClassVar[str]
    matched_density: float
    radial_extent: float | None
    def __init__(
        self,
        *,
        matched_density: float,
        radial_extent: float | None = None,
    ) -> None:
        """Add radial matched profile dependence to a z-dependent density function.

        The resulting function has the form:
        density(z, r) = n_p0(z) * (1 + r^2 / (pi * r_e * n_p0(z) * w_m^4))

        where:
        - n_p0(z) is the z-dependent density profile (z_density_func)
        - r_e is the classical electron radius
        - w_m is the matched spot size parameter, calculated using plasma density

        This radial profile represents a matched beam envelope condition where the
        radial modulation depends on the local plasma density.

        Args:
            matched_density: (float) [m^-3] Nominal plasma density in m^-3 used to scale the matched spot size parameter.
                This may be unique from the base density profile's nominal density.
            radial_extent: float | None [m] |OPTIONAL| Radial extent of the density profile. If None, the radial extent is determined by the simulation grid."""
    def get_z_extent(self) -> tuple[float, float] | None:
        ...
    def get_r_extent(self) -> float | None:
        ...
    def modify_density_function(self, density_function: DensityCallable) -> DensityCallable:
        ...

class ModifiedDensityProfile(_DensityProfile):
    """Apply density modifiers on top of another density profile.

    Particle counts, species, and other simulation parameters are inherited from
    ``base_density_profile`` and are not serialized on this config.

    Args:
        base_density_profile: (DensityProfile) The base density profile.
        modifiers: (DensityModifier|list[DensityModifier]) The modifiers to apply to the density profile.
        nominal_density: (float) [m^-3] Baseline (nominal) plasma density in m^-3 used to scale
            the relative profile returned by `build_density_function` (which is normalized to 1).
        species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
            If None, the plasma is assumed to be fully ionized and no ionization is considered.
            If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
            Defaults to Hydrogen.
        ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
            Defaults to unionized (ionization level 0).
        p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
        p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
        p_nr: (int) Number of macroparticles per gridcell along the radial direction.
        p_nt: (int) Number of macroparticles per gridcell along the angular direction.
        elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
        elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
            Defaults to None.
        ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
        ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Defaults to None."""
    SUBCLASS: ClassVar[str]
    nominal_density: float
    p_nz: int
    p_nr: int
    p_nt: int
    species: str | None
    ionization: int | None
    p_rmax: float | None
    elec_name: str | None
    elec_select: dict[str, list[float | None]] | None
    ion_name: str | None
    ion_select: dict[str, list[float | None]] | None
    base_density_profile: _DensityProfile | Path | str | dict
    modifiers: _DensityModifier | Path | str | dict | List[_DensityModifier | Path | str | dict]
    resolved_base_density_profile: _DensityProfile
    resolved_modifiers: list[_DensityModifier]
    def __init__(
        self,
        *,
        base_density_profile: _DensityProfile | Path | str | dict,
        modifiers: _DensityModifier | Path | str | dict | List[_DensityModifier | Path | str | dict] = [],
    ) -> None:
        """Apply density modifiers on top of another density profile.

        Particle counts, species, and other simulation parameters are inherited from
        ``base_density_profile`` and are not serialized on this config.

        Args:
            base_density_profile: (DensityProfile) The base density profile.
            modifiers: (DensityModifier|list[DensityModifier]) The modifiers to apply to the density profile.
            nominal_density: (float) [m^-3] Baseline (nominal) plasma density in m^-3 used to scale
                the relative profile returned by `build_density_function` (which is normalized to 1).
            species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
                If None, the plasma is assumed to be fully ionized and no ionization is considered.
                If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
                Defaults to Hydrogen.
            ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
                Defaults to unionized (ionization level 0).
            p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
            p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
            p_nr: (int) Number of macroparticles per gridcell along the radial direction.
            p_nt: (int) Number of macroparticles per gridcell along the angular direction.
            elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
            elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
                Defaults to None.
            ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
            ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Defaults to None."""
    def get_z_extent(self) -> tuple[float, float] | None:
        ...
    def get_r_extent(self) -> float | None:
        ...
    def build_density_function(self) -> DensityCallable:
        ...
