# Auto-generated by tools/sync_config_docstrings.py — do not edit by hand.

from __future__ import annotations

from .serializable_config import SerializableConfig

from abc import abstractmethod
from fbpic.main import Simulation as FBPICSimulation
from fbpic.particles.particles import Particles
from pathlib import Path
from typing import TYPE_CHECKING, Any, Callable, ClassVar
import matplotlib.pyplot as plt
import numpy as np
import numpy.typing as npt

DensityCallable = Callable[[npt.ArrayLike, npt.ArrayLike], npt.ArrayLike]

class _DensityModifier(SerializableConfig):
    """Base class for serializable density modifier configurations."""
    CONFIG_TYPE: ClassVar[str]
    @abstractmethod
    def modify_density_function(self, density_function: DensityCallable) -> DensityCallable:
        """Modify the density function.

        Args:
            density_function: (DensityCallable) The density function to modify.

        Returns:
            DensityCallable: The modified density function."""
        ...
    @abstractmethod
    def get_z_extent(self) -> tuple[float, float]:
        """Get the longitudinal extent of the density profile in meters.

        Returns:
            tuple[float, float]: A tuple of (z_min, z_max) representing the longitudinal extent in meters."""
        ...
    @abstractmethod
    def get_r_extent(self) -> float | None:
        """Get the radial extent of the density profile in meters.

        Returns:
            float|None: The radial extent in meters, or None if not applicable."""
        ...

class _DensityProfile(SerializableConfig):
    """Base class for serializable density profile configurations.

    Args:
        nominal_density: (float) [m^-3] Baseline (nominal) plasma density in m^-3 used to scale
            the relative profile returned by `build_density_function` (which is normalized to 1).
        p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
        p_nr: (int) Number of macroparticles per gridcell along the radial direction.
        p_nt: (int) Number of macroparticles per gridcell along the angular direction.
        species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
            If None, the plasma is assumed to be fully ionized and no ionization is considered.
            If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
            Defaults to Hydrogen.
        ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
            Defaults to unionized (ionization level 0).
        p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
        elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
        elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
            Defaults to None.
        ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
        ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Defaults to None."""
    nominal_density: float
    p_nz: int
    p_nr: int
    p_nt: int
    species: str | None
    ionization: int | None
    p_rmax: float | None
    elec_name: str | None
    elec_select: dict[str, list[float | None]] | None
    ion_name: str | None
    ion_select: dict[str, list[float | None]] | None
    CONFIG_TYPE: ClassVar[str]
    def __init__(
        self,
        *,
        nominal_density: float,
        p_nz: int,
        p_nr: int,
        p_nt: int,
        species: str | None = 'H',
        ionization: int | None = 0,
        p_rmax: float | None = None,
        elec_name: str | None = None,
        elec_select: dict[str, list[float | None]] | None = None,
        ion_name: str | None = None,
        ion_select: dict[str, list[float | None]] | None = None,
    ) -> None:
        """Base class for serializable density profile configurations.

        Args:
            nominal_density: (float) [m^-3] Baseline (nominal) plasma density in m^-3 used to scale
                the relative profile returned by `build_density_function` (which is normalized to 1).
            p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
            p_nr: (int) Number of macroparticles per gridcell along the radial direction.
            p_nt: (int) Number of macroparticles per gridcell along the angular direction.
            species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
                If None, the plasma is assumed to be fully ionized and no ionization is considered.
                If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
                Defaults to Hydrogen.
            ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
                Defaults to unionized (ionization level 0).
            p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
            elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
            elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
                Defaults to None.
            ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
            ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Defaults to None."""
    @abstractmethod
    def get_z_extent(self) -> tuple[float, float]:
        """Get the longitudinal extent of the density profile in meters.

        Returns:
            tuple[float, float]: A tuple of (z_min, z_max) representing the longitudinal extent in meters."""
        ...
    @abstractmethod
    def get_r_extent(self) -> float | None:
        """Get the radial extent of the density profile in meters.

        Returns:
            float|None: The radial extent in meters, or None if not applicable."""
        ...
    @abstractmethod
    def build_density_function(self) -> DensityCallable:
        """Return a callable function that returns the relative density at position (z, r).
        The function takes two arguments:
            z: Array-like of z positions
            r: Array-like of r positions
        and returns an array-like of density values.

        Returns:
            DensityCallable: A callable function that returns the relative density at position (z, r)."""
        ...
    def plot_z_profile(self, ax: plt.Axes, num: int=100, r0: float=0.0, z_scale: float=1.0, density_scale: float=1.0, z_padding_fraction: float=0.0, neutral_density: bool=False, **kwargs: Any) -> tuple[npt.NDArray[np.floating], npt.NDArray[np.floating]]:
        """Plot the on-axis (z) density profile on the given axes.

        Args:
            ax: (matplotlib.axes.Axes object) The axes to plot on.
            num: (int) The number of points to plot.
            r0: (float) The r position to plot at.
            z_scale: (float) The scale to apply to the z axis.
                Defaults to 1.0.
            density_scale: (float) The scale to apply to the density axis.
                Defaults to 1.0.
            z_padding_fraction: (float) Fractional padding applied to the z
                extent on each side.
            neutral_density: (bool) Whether to plot the neutral density or the
                fully ionized electron density.
            **kwargs: Additional arguments to pass to the plot function.

        Returns:
            tuple[npt.NDArray[np.floating], npt.NDArray[np.floating]]: Tuple of (z positions [m], density values [m^-3])."""
        ...
    def plot_r_profile(self, ax: plt.Axes, num: int=100, z0: float=0.0, r_scale: float=1.0, density_scale: float=1.0, r_max: float=None, **kwargs: Any) -> None:
        """Plot the density profile on the given axes.

        Args:
            ax: (matplotlib.axes.Axes object) The axes to plot on.
            num: (int) The number of points to plot.
            z0: (float) The z position to plot at.
            r_scale: (float) The scale to apply to the r axis.
                Defaults to 1.0.
            density_scale: (float) The scale to apply to the density axis.
                Defaults to 1.0.
            r_max: (float) The maximum r position to plot at.
                Defaults to None.
            **kwargs: Additional arguments to pass to the plot function.

        Returns:
            None."""
        ...
    def plot(self, *, neutral_density: bool=False, ax: plt.Axes | None=None, r_max: float | None=None, num: int=600, z_padding_fraction: float=0.0, default_r_max: float=5e-05, output_path: Path | str | None=None, show: bool=False, label: str | None=None) -> plt.Figure:
        """Plot the density profile as an on-axis lineout and 2D z-r map.

        Args:
            neutral_density: (bool) Whether to plot the neutral density or the fully ionized electron density.
            ax: (matplotlib.axes.Axes|None) If provided, the on-axis lineout is
                *also* drawn on this external axes (useful for combined overlay
                figures). The method still creates its own figure.
            r_max: (float|None) [m] Maximum radial extent for the 2D map. If
                *None*, resolved from ``get_r_extent()`` / ``p_rmax`` /
                *default_r_max*.
            num: (int) Grid resolution along each axis.
            z_padding_fraction: (float) Fractional padding applied to the z
                extent on each side.
            default_r_max: (float) [m] Fallback radial extent when the profile
                does not specify one.
            output_path: (Path|str|None) If given, the figure is saved to this
                path.
            show: (bool) Whether to call ``plt.show()``.
            label: (str|None) Label used on the external *ax* lineout. Defaults
                to ``self.SUBCLASS (self.species)``.

        Returns:
            pyplot.Figure: The created matplotlib Figure."""
        ...
    def get_plasma_wavelength(self, z: float | None=None, r: float | None=None) -> float:
        """Get the plasma wavelength at a given position. If no position is provided,
        return the plasma wavelength according to the "nominal_density" parameter.

        Args:
            z: (float|None) The z position to evaluate the plasma wavelength at.
                If None, the plasma wavelength is evaluated at z=0.0.
            r: (float|None) The r position to evaluate the plasma wavelength at.
                If None, the plasma wavelength is evaluated at r=0.0.

        Returns:
            float: The plasma wavelength at the given position. If the plasma density is zero at the given position, return infinity."""
        ...
    def add_to_simulation(self, simulation: FBPICSimulation, is_boosted: bool) -> tuple[Particles, Particles | None]:
        """Add gas to the simulation.

        Args:
            simulation: (FBPICSimulation) The simulation to add the density profile to.
            is_boosted: (bool) Whether the simulation is boosted. If True and species is None, Hydrogen will be assumed.

        Returns:
            tuple[Particles, Particles | None]: A tuple containing the added electron species and the added ion species if it exists, otherwise None (e.g., electron-only)."""
        ...
