# Auto-generated by tools/sync_config_docstrings.py — do not edit by hand.

from __future__ import annotations

from .density_core import _DensityProfile

from collections.abc import Mapping
from inversion_fbpic.lib.density_core import _DensityProfile, DensityCallable
from typing import ClassVar, Iterator
import numpy.typing as npt

from ._density_implementations.generic_conical_target import GenericConicalTarget as GenericConicalTarget
from ._density_implementations.generic_conical_target import PowerLawFlattop as PowerLawFlattop
from ._density_implementations.interpolate_from_h5_profile import InterpolateFromH5Profile as InterpolateFromH5Profile

class GeneralizedLorentzianParameters:
    """Parameters for a generalized Lorentzian term:
    A[1+|(s-c)/w|^b]^{-m}

    Args:
        A: (float) [m^-3] amplitude
        c: (float) [m] center
        w: (float) [m] width
        b: (float) inner exponent
        m: (float) outer exponent"""
    A: float
    c: float
    w: float
    b: float
    m: float
    def __init__(
        self,
        *,
        A: float,
        c: float,
        w: float,
        b: float,
        m: float,
    ) -> None:
        """Parameters for a generalized Lorentzian term:
        A[1+|(s-c)/w|^b]^{-m}

        Args:
            A: (float) [m^-3] amplitude
            c: (float) [m] center
            w: (float) [m] width
            b: (float) inner exponent
            m: (float) outer exponent"""
    @classmethod
    def from_mapping(cls, parameters: 'GeneralizedLorentzianParameters | Mapping[str, float]') -> 'GeneralizedLorentzianParameters':
        ...
    @classmethod
    def normalize(cls, parameters: 'GeneralizedLorentzianParameters | Mapping[str, float] | list[GeneralizedLorentzianParameters | Mapping[str, float]]') -> list['GeneralizedLorentzianParameters']:
        ...
    def z_extent(self, density_cutoff_ratio: float=0.001) -> tuple[float, float]:
        """Get the z extent of the generalized Lorentzian term based on the density cutoff ratio."""
        ...
    def dens_func(self, z: npt.ArrayLike) -> npt.ArrayLike:
        """Return the density function for the generalized Lorentzian term. May contain negative values!"""
        ...

class AsymmetricSine(_DensityProfile):
    """Asymmetric sine-squared density profile.
    The profile is a combination of a sine-squared upramp of a specified length and a corresponding downramp of another specified length.

    Args:
        nominal_density: (float) [m^-3] Baseline (nominal) plasma density in m^-3 used to scale
            the relative profile returned by `build_density_function` (which is normalized to 1).
        p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
        p_nr: (int) Number of macroparticles per gridcell along the radial direction.
        p_nt: (int) Number of macroparticles per gridcell along the angular direction.
        species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
            If None, the plasma is assumed to be fully ionized and no ionization is considered.
            If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
            Defaults to Hydrogen.
        ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
            Defaults to unionized (ionization level 0).
        p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
        elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
        elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
            Defaults to None.
        ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
        ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Defaults to None.
        peak_z0: (float) [m] Position of the maximum of the profile.
        upramp_length: (float) [m] Length of the upramp.
        downramp_length: (float) [m] Length of the downramp."""
    SUBCLASS: ClassVar[str]
    peak_z0: float
    upramp_length: float
    downramp_length: float
    def __init__(
        self,
        *,
        nominal_density: float,
        p_nz: int,
        p_nr: int,
        p_nt: int,
        species: str | None = 'H',
        ionization: int | None = 0,
        p_rmax: float | None = None,
        elec_name: str | None = None,
        elec_select: dict[str, list[float | None]] | None = None,
        ion_name: str | None = None,
        ion_select: dict[str, list[float | None]] | None = None,
        peak_z0: float,
        upramp_length: float,
        downramp_length: float,
    ) -> None:
        """Asymmetric sine-squared density profile.
        The profile is a combination of a sine-squared upramp of a specified length and a corresponding downramp of another specified length.

        Args:
            nominal_density: (float) [m^-3] Baseline (nominal) plasma density in m^-3 used to scale
                the relative profile returned by `build_density_function` (which is normalized to 1).
            p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
            p_nr: (int) Number of macroparticles per gridcell along the radial direction.
            p_nt: (int) Number of macroparticles per gridcell along the angular direction.
            species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
                If None, the plasma is assumed to be fully ionized and no ionization is considered.
                If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
                Defaults to Hydrogen.
            ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
                Defaults to unionized (ionization level 0).
            p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
            elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
            elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
                Defaults to None.
            ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
            ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Defaults to None.
            peak_z0: (float) [m] Position of the maximum of the profile.
            upramp_length: (float) [m] Length of the upramp.
            downramp_length: (float) [m] Length of the downramp."""
    def get_z_extent(self) -> tuple[float, float]:
        ...
    def get_r_extent(self) -> float | None:
        ...
    def build_density_function(self) -> DensityCallable:
        ...

class ExampleDensityProfile(_DensityProfile):
    """Finite sine-squared density bump profile.

    Args:
        nominal_density: (float) [m^-3] Baseline (nominal) plasma density in m^-3 used to scale
            the relative profile returned by `build_density_function` (which is normalized to 1).
        p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
        p_nr: (int) Number of macroparticles per gridcell along the radial direction.
        p_nt: (int) Number of macroparticles per gridcell along the angular direction.
        species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
            If None, the plasma is assumed to be fully ionized and no ionization is considered.
            If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
            Defaults to Hydrogen.
        ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
            Defaults to unionized (ionization level 0).
        p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
        elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
        elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
            Defaults to None.
        ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
        ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Defaults to None.
        length: (float) [m] Total length of the finite sine-squared support in meters.
            The profile is non-zero only over this interval.
        start_position: (float) [m] |OPTIONAL| z position in meters where the profile support starts. Defaults to 0.0."""
    SUBCLASS: ClassVar[str]
    length: float
    start_position: float
    def __init__(
        self,
        *,
        nominal_density: float,
        p_nz: int,
        p_nr: int,
        p_nt: int,
        species: str | None = 'H',
        ionization: int | None = 0,
        p_rmax: float | None = None,
        elec_name: str | None = None,
        elec_select: dict[str, list[float | None]] | None = None,
        ion_name: str | None = None,
        ion_select: dict[str, list[float | None]] | None = None,
        length: float,
        start_position: float = 0.0,
    ) -> None:
        """Finite sine-squared density bump profile.

        Args:
            nominal_density: (float) [m^-3] Baseline (nominal) plasma density in m^-3 used to scale
                the relative profile returned by `build_density_function` (which is normalized to 1).
            p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
            p_nr: (int) Number of macroparticles per gridcell along the radial direction.
            p_nt: (int) Number of macroparticles per gridcell along the angular direction.
            species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
                If None, the plasma is assumed to be fully ionized and no ionization is considered.
                If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
                Defaults to Hydrogen.
            ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
                Defaults to unionized (ionization level 0).
            p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
            elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
            elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
                Defaults to None.
            ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
            ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Defaults to None.
            length: (float) [m] Total length of the finite sine-squared support in meters.
                The profile is non-zero only over this interval.
            start_position: (float) [m] |OPTIONAL| z position in meters where the profile support starts. Defaults to 0.0."""
    def get_z_extent(self) -> tuple[float, float]:
        """Get the longitudinal extent of the density profile in meters."""
        ...
    def get_r_extent(self) -> float | None:
        """Get the radial extent of the density profile in meters."""
        ...
    def build_density_function(self) -> DensityCallable:
        """Return a finite sine-squared n(z, r) profile.

        Returns:
            A callable function that returns the relative density at position (z, r).
            The function takes two arguments:
                z: Array-like of z positions
                r: Array-like of r positions
            and returns an array-like of density values."""
        ...

class GaussianPlusTriangle(_DensityProfile):
    """Gaussian plus triangle density profile in z.

    Args:
        nominal_density: (float) [m^-3] Baseline (nominal) plasma density in m^-3 used to scale
            the relative profile returned by `build_density_function` (which is normalized to 1).
        p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
        p_nr: (int) Number of macroparticles per gridcell along the radial direction.
        p_nt: (int) Number of macroparticles per gridcell along the angular direction.
        species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
            If None, the plasma is assumed to be fully ionized and no ionization is considered.
            If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
            Defaults to Hydrogen.
        ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
            Defaults to unionized (ionization level 0).
        p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
        elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
        elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
            Defaults to None.
        ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
        ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Defaults to None.
        gauss_sigma: (float) [m] Standard deviation of the Gaussian in z.
        gauss_z0: (float) [m] Center position of the Gaussian in z.
        tri_z0: (float) [m] Center (tip) position of the triangle in z.
        tri_left_width: (float) [m] Length scale of the triangle to the left of the tip.
        tri_right_width: (float) [m] Length scale of the triangle to the right of the tip.
        tri_height: (float) [m] |OPTIONAL| Height of the triangle at the tip with respect to the Gaussian amplitude. Defaults to 1.0.
        num_sigma_extent: (float) |OPTIONAL| Number of sigma's to account for in the longitudinal extent of the Gaussian component. Defaults to 3.0."""
    SUBCLASS: ClassVar[str]
    gauss_sigma: float
    gauss_z0: float
    tri_z0: float
    tri_left_width: float
    tri_right_width: float
    tri_height: float
    num_sigma_extent: float
    def __init__(
        self,
        *,
        nominal_density: float,
        p_nz: int,
        p_nr: int,
        p_nt: int,
        species: str | None = 'H',
        ionization: int | None = 0,
        p_rmax: float | None = None,
        elec_name: str | None = None,
        elec_select: dict[str, list[float | None]] | None = None,
        ion_name: str | None = None,
        ion_select: dict[str, list[float | None]] | None = None,
        gauss_sigma: float,
        gauss_z0: float,
        tri_z0: float,
        tri_left_width: float,
        tri_right_width: float,
        tri_height: float = 1.0,
        num_sigma_extent: float = 3.0,
    ) -> None:
        """Gaussian plus triangle density profile in z.

        Args:
            nominal_density: (float) [m^-3] Baseline (nominal) plasma density in m^-3 used to scale
                the relative profile returned by `build_density_function` (which is normalized to 1).
            p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
            p_nr: (int) Number of macroparticles per gridcell along the radial direction.
            p_nt: (int) Number of macroparticles per gridcell along the angular direction.
            species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
                If None, the plasma is assumed to be fully ionized and no ionization is considered.
                If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
                Defaults to Hydrogen.
            ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
                Defaults to unionized (ionization level 0).
            p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
            elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
            elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
                Defaults to None.
            ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
            ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Defaults to None.
            gauss_sigma: (float) [m] Standard deviation of the Gaussian in z.
            gauss_z0: (float) [m] Center position of the Gaussian in z.
            tri_z0: (float) [m] Center (tip) position of the triangle in z.
            tri_left_width: (float) [m] Length scale of the triangle to the left of the tip.
            tri_right_width: (float) [m] Length scale of the triangle to the right of the tip.
            tri_height: (float) [m] |OPTIONAL| Height of the triangle at the tip with respect to the Gaussian amplitude. Defaults to 1.0.
            num_sigma_extent: (float) |OPTIONAL| Number of sigma's to account for in the longitudinal extent of the Gaussian component. Defaults to 3.0."""
    def get_z_extent(self) -> tuple[float, float]:
        ...
    def get_r_extent(self) -> float | None:
        ...
    def build_density_function(self) -> DensityCallable:
        ...

class GeneralizedGaussianPlusTriangle(_DensityProfile):
    """Generalized Gaussian plus triangle density profile in z.

    Args:
        nominal_density: (float) [m^-3] Baseline (nominal) plasma density in m^-3 used to scale
            the relative profile returned by `build_density_function` (which is normalized to 1).
        p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
        p_nr: (int) Number of macroparticles per gridcell along the radial direction.
        p_nt: (int) Number of macroparticles per gridcell along the angular direction.
        species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
            If None, the plasma is assumed to be fully ionized and no ionization is considered.
            If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
            Defaults to Hydrogen.
        ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
            Defaults to unionized (ionization level 0).
        p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
        elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
        elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
            Defaults to None.
        ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
        ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Defaults to None.
        gauss_peak: (float) Peak value of the generalized Gaussian.
        gauss_alpha: (float) [m] Scale parameter of the generalized Gaussian.
        gauss_beta: (float) Shape parameter of the generalized Gaussian.
        gauss_z0: (float) [m] Center position of the generalized Gaussian in z.
        tri_z0: (float) [m] Center (tip) position of the triangle in z.
        tri_left_width: (float) [m] Length scale of the triangle to the left of the tip.
        tri_right_width: (float) [m] Length scale of the triangle to the right of the tip.
        tri_height: (float) [m] Height of the triangle at the tip with respect to the generalized Gaussian amplitude.
        num_sigma_extent: (float) |OPTIONAL| Number of sigma's to account for in the longitudinal extent of the Gaussian component. Defaults to 3.0."""
    SUBCLASS: ClassVar[str]
    gauss_peak: float
    gauss_alpha: float
    gauss_beta: float
    gauss_z0: float
    tri_z0: float
    tri_left_width: float
    tri_right_width: float
    tri_height: float
    num_sigma_extent: float
    def __init__(
        self,
        *,
        nominal_density: float,
        p_nz: int,
        p_nr: int,
        p_nt: int,
        species: str | None = 'H',
        ionization: int | None = 0,
        p_rmax: float | None = None,
        elec_name: str | None = None,
        elec_select: dict[str, list[float | None]] | None = None,
        ion_name: str | None = None,
        ion_select: dict[str, list[float | None]] | None = None,
        gauss_peak: float,
        gauss_alpha: float,
        gauss_beta: float,
        gauss_z0: float,
        tri_z0: float,
        tri_left_width: float,
        tri_right_width: float,
        tri_height: float,
        num_sigma_extent: float = 3.0,
    ) -> None:
        """Generalized Gaussian plus triangle density profile in z.

        Args:
            nominal_density: (float) [m^-3] Baseline (nominal) plasma density in m^-3 used to scale
                the relative profile returned by `build_density_function` (which is normalized to 1).
            p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
            p_nr: (int) Number of macroparticles per gridcell along the radial direction.
            p_nt: (int) Number of macroparticles per gridcell along the angular direction.
            species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
                If None, the plasma is assumed to be fully ionized and no ionization is considered.
                If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
                Defaults to Hydrogen.
            ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
                Defaults to unionized (ionization level 0).
            p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
            elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
            elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
                Defaults to None.
            ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
            ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Defaults to None.
            gauss_peak: (float) Peak value of the generalized Gaussian.
            gauss_alpha: (float) [m] Scale parameter of the generalized Gaussian.
            gauss_beta: (float) Shape parameter of the generalized Gaussian.
            gauss_z0: (float) [m] Center position of the generalized Gaussian in z.
            tri_z0: (float) [m] Center (tip) position of the triangle in z.
            tri_left_width: (float) [m] Length scale of the triangle to the left of the tip.
            tri_right_width: (float) [m] Length scale of the triangle to the right of the tip.
            tri_height: (float) [m] Height of the triangle at the tip with respect to the generalized Gaussian amplitude.
            num_sigma_extent: (float) |OPTIONAL| Number of sigma's to account for in the longitudinal extent of the Gaussian component. Defaults to 3.0."""
    def get_z_extent(self) -> tuple[float, float]:
        ...
    def get_r_extent(self) -> float | None:
        ...
    def build_density_function(self) -> DensityCallable:
        ...

class GeneralizedLorentzianSum(_DensityProfile):
    """Summed series of generalized Lorentzian terms:
    n(z) = sum_i A_i [1 + |(z - c_i)/w_i|^b_i]^{-m_i}

    Args:
        p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
        p_nr: (int) Number of macroparticles per gridcell along the radial direction.
        p_nt: (int) Number of macroparticles per gridcell along the angular direction.
        species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
            If None, the plasma is assumed to be fully ionized and no ionization is considered.
            If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
            Defaults to Hydrogen.
        ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
            Defaults to unionized (ionization level 0).
        p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
        elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
        elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
            Defaults to None.
        ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
        ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Defaults to None.
        parameters: (list[GeneralizedLorentzianParameters]|GeneralizedLorentzianParameters) Parameters or list of parameters for each generalized Lorentzian term.
        density_cutoff_ratio: (float) |OPTIONAL| Ratio of the density cutoff to the maximum density. The guaranteed minimum density ratio relative to the maximal component at the edges is the number of terms times this value. Defaults to 1e-3.
        nominal_density: (float) [m^-3] |NOT REFERENCED| The maximal density contribution for an individual Lorentzian for this profile. This quantity is determined by the dataset used."""
    SUBCLASS: ClassVar[str]
    parameters: list[GeneralizedLorentzianParameters]
    density_cutoff_ratio: float
    nominal_density: float
    def __init__(
        self,
        *,
        p_nz: int,
        p_nr: int,
        p_nt: int,
        species: str | None = 'H',
        ionization: int | None = 0,
        p_rmax: float | None = None,
        elec_name: str | None = None,
        elec_select: dict[str, list[float | None]] | None = None,
        ion_name: str | None = None,
        ion_select: dict[str, list[float | None]] | None = None,
        parameters: list[GeneralizedLorentzianParameters],
        density_cutoff_ratio: float = 0.001,
    ) -> None:
        """Summed series of generalized Lorentzian terms:
        n(z) = sum_i A_i [1 + |(z - c_i)/w_i|^b_i]^{-m_i}

        Args:
            p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
            p_nr: (int) Number of macroparticles per gridcell along the radial direction.
            p_nt: (int) Number of macroparticles per gridcell along the angular direction.
            species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
                If None, the plasma is assumed to be fully ionized and no ionization is considered.
                If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
                Defaults to Hydrogen.
            ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
                Defaults to unionized (ionization level 0).
            p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
            elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
            elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
                Defaults to None.
            ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
            ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Defaults to None.
            parameters: (list[GeneralizedLorentzianParameters]|GeneralizedLorentzianParameters) Parameters or list of parameters for each generalized Lorentzian term.
            density_cutoff_ratio: (float) |OPTIONAL| Ratio of the density cutoff to the maximum density. The guaranteed minimum density ratio relative to the maximal component at the edges is the number of terms times this value. Defaults to 1e-3.
            nominal_density: (float) [m^-3] |NOT REFERENCED| The maximal density contribution for an individual Lorentzian for this profile. This quantity is determined by the dataset used."""
    def get_z_extent(self) -> tuple[float, float]:
        ...
    def get_r_extent(self) -> float | None:
        ...
    def build_density_function(self) -> DensityCallable:
        ...

class SmoothSineFlattop(_DensityProfile):
    """Smooth flattop density profile. The upramp and downramp on either side are cosine-squared functions.
    The profile is nonzero, starting at offset_length; the flattop starts at offset_length + upramp_length.

    Args:
        nominal_density: (float) [m^-3] Baseline (nominal) plasma density in m^-3 used to scale
            the relative profile returned by `build_density_function` (which is normalized to 1).
        p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
        p_nr: (int) Number of macroparticles per gridcell along the radial direction.
        p_nt: (int) Number of macroparticles per gridcell along the angular direction.
        species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
            If None, the plasma is assumed to be fully ionized and no ionization is considered.
            If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
            Defaults to Hydrogen.
        ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
            Defaults to unionized (ionization level 0).
        p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
        elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
        elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
            Defaults to None.
        ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
        ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
            The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
            Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
            Defaults to None.
        flattop_width: (float) [m] Width of the flattop.
        upramp_length: (float) [m] Length of the upramp.
        downramp_length: (float) [m] Length of the downramp.
        offset_length: (float) [m] |OPTIONAL| Offset of the profile. Defaults to 0.0."""
    SUBCLASS: ClassVar[str]
    flattop_width: float
    upramp_length: float
    downramp_length: float
    offset_length: float
    def __init__(
        self,
        *,
        nominal_density: float,
        p_nz: int,
        p_nr: int,
        p_nt: int,
        species: str | None = 'H',
        ionization: int | None = 0,
        p_rmax: float | None = None,
        elec_name: str | None = None,
        elec_select: dict[str, list[float | None]] | None = None,
        ion_name: str | None = None,
        ion_select: dict[str, list[float | None]] | None = None,
        flattop_width: float,
        upramp_length: float,
        downramp_length: float,
        offset_length: float = 0.0,
    ) -> None:
        """Smooth flattop density profile. The upramp and downramp on either side are cosine-squared functions.
        The profile is nonzero, starting at offset_length; the flattop starts at offset_length + upramp_length.

        Args:
            nominal_density: (float) [m^-3] Baseline (nominal) plasma density in m^-3 used to scale
                the relative profile returned by `build_density_function` (which is normalized to 1).
            p_nz: (int) Number of macroparticles per gridcell along the longitudinal direction.
            p_nr: (int) Number of macroparticles per gridcell along the radial direction.
            p_nt: (int) Number of macroparticles per gridcell along the angular direction.
            species: (str|None) [str] |OPTIONAL| Species name for the density profile. Should be the one- or two-character code for the species.
                If None, the plasma is assumed to be fully ionized and no ionization is considered.
                If the gamma boost factor is used in the simulation, Hydrogen will be assumed if species is None.
                Defaults to Hydrogen.
            ionization: (int|None) [int] |OPTIONAL| Initial ionization level for this species. If None or 0, the plasma is assumed to be initially unionized. If -1, the plasma is assumed to be fully ionized.
                Defaults to unionized (ionization level 0).
            p_rmax: (float|None) [m] |OPTIONAL| Maximum radial extent of the density profile. If None, the radial extent is determined by the simulation grid.
            elec_name: (str|None) [str] |OPTIONAL| Name of the electron species when writing diagnostics. If None, the electron particles will not be written to diagnostics.
            elec_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the electron species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example Python: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Example YAML: elec_select: {uz: [10.0, null], z: [-1.0e-6, 1.0e-6]}
                Defaults to None.
            ion_name: (str|None) [str] |OPTIONAL| Name of the ion species when writing diagnostics. If None, the ion particles will not be written to diagnostics.
            ion_select: (dict[str, list[float|None]]|None) [dict] |OPTIONAL| Filters for the ion species when writing diagnostics.
                The keys are the names of the particle attributes to filter on, and the values are the minimum and maximum values for the attribute. If None, no filter is applied.
                Example: {"uz": [10.0, None], "z": [-1e-6, 1e-6]} will filter on the uz and z attributes, keeping only particles with uz > 10.0 and z between -1e-6 and 1e-6.
                Defaults to None.
            flattop_width: (float) [m] Width of the flattop.
            upramp_length: (float) [m] Length of the upramp.
            downramp_length: (float) [m] Length of the downramp.
            offset_length: (float) [m] |OPTIONAL| Offset of the profile. Defaults to 0.0."""
    def get_z_extent(self) -> tuple[float, float]:
        ...
    def get_r_extent(self) -> float | None:
        ...
    def build_density_function(self) -> DensityCallable:
        ...
