# Auto-generated by tools/sync_config_docstrings.py — do not edit by hand.

from __future__ import annotations

from .serializable_config import SerializableConfig

from abc import abstractmethod
from fbpic.lpa_utils.laser.laser_profiles import LaserProfile
from pathlib import Path
from typing import Any, Callable, ClassVar, TYPE_CHECKING, Literal, Iterable
import matplotlib.pyplot as plt

class _LaserPulse(SerializableConfig):
    """Base class for serializable laser profile configurations.

    Provide exactly one of ``energy`` or ``a0``; the other is derived from beam
    parameters at construction time.  When serialized (YAML / JSON) the derived
    companion is written as ``out_a0`` or ``out_energy`` for reference but is
    ignored on load.

    Args:
        energy: (float|None) [J] |OPTIONAL| Energy of the laser pulse in Joules. Provide this or a0, not both.
        a0: (float|None) |OPTIONAL| Normalized laser amplitude parameter. Provide this or energy, not both.
        z0: (float) [m] Position of the laser pulse within the simulation window in meters.
        method: (Literal["direct", "antenna"]|None) |OPTIONAL| Method to use for laser pulse propagation. If None, the laser pulse will be propagated using the direct method.
        z0_antenna: (float|None) [m] |OPTIONAL| Position of the antenna within the simulation window in meters. Required if method is "antenna".
        v_antenna: (float|None) [m/s] |OPTIONAL| Velocity of the antenna in meters per second. Required if method is "antenna"."""
    energy: float | None
    a0: float | None
    z0: float
    method: Literal['direct', 'antenna'] | None
    z0_antenna: float | None
    v_antenna: float | None
    out_a0: float | None
    out_energy: float | None
    CONFIG_TYPE: ClassVar[str]
    def __init__(
        self,
        *,
        energy: float | None = None,
        a0: float | None = None,
        z0: float,
        method: Literal['direct', 'antenna'] | None = None,
        z0_antenna: float | None = None,
        v_antenna: float | None = None,
    ) -> None:
        """Base class for serializable laser profile configurations.

        Provide exactly one of ``energy`` or ``a0``; the other is derived from beam
        parameters at construction time.  When serialized (YAML / JSON) the derived
        companion is written as ``out_a0`` or ``out_energy`` for reference but is
        ignored on load.

        Args:
            energy: (float|None) [J] |OPTIONAL| Energy of the laser pulse in Joules. Provide this or a0, not both.
            a0: (float|None) |OPTIONAL| Normalized laser amplitude parameter. Provide this or energy, not both.
            z0: (float) [m] Position of the laser pulse within the simulation window in meters.
            method: (Literal["direct", "antenna"]|None) |OPTIONAL| Method to use for laser pulse propagation. If None, the laser pulse will be propagated using the direct method.
            z0_antenna: (float|None) [m] |OPTIONAL| Position of the antenna within the simulation window in meters. Required if method is "antenna".
            v_antenna: (float|None) [m/s] |OPTIONAL| Velocity of the antenna in meters per second. Required if method is "antenna"."""
    def to_dict(self, *, include_nones: bool=True) -> dict[str, Any]:
        ...
    @classmethod
    def from_dict(cls, payload: dict[str, Any], *, overrides: dict[str, Any] | None=None) -> '_LaserPulse':
        ...
    def get_z_extent(self, num_sigma: float=3.0) -> tuple[float, float]:
        """Get the longitudinal extent of the laser pulse in meters.

        Args:
            num_sigma: (float) Number of sigmas to account for in the longitudinal extent.

        Returns:
            tuple[float, float]: The longitudinal extent of the laser pulse in meters."""
        ...
    @abstractmethod
    def plot(self, *, mode: Literal['lineout', 'lineout_and_2d']='lineout_and_2d', ax: 'plt.Axes | None'=None, num: int=600, output_path: Path | str | None=None, show: bool=False, label: str | None=None) -> 'plt.Figure':
        """Plot the laser pulse envelope and (optionally) a face-on x-y cross-section.

        Args:
            mode: (Literal["lineout", "lineout_and_2d"]) Panel layout.
                ``"lineout"`` shows only the longitudinal envelope.
                ``"lineout_and_2d"`` (default) adds a face-on x-y field-amplitude
                map at the focal plane with a quiver overlay showing polarization.
            ax: (matplotlib.axes.Axes|None) If provided, the longitudinal envelope
                is also drawn on this external axes (for combined overlay figures).
            num: (int) Grid resolution along each axis.
            output_path: (Path|str|None) If given, the figure is saved here.
            show: (bool) Whether to call ``plt.show()``.
            label: (str|None) Label for the external *ax* lineout. Defaults to
                ``SUBCLASS (polarization)``.

        Returns:
            The created matplotlib Figure."""
        ...
    @abstractmethod
    def get_r_extent(self, simulation_extent: tuple[float, float], num_sigma: float=3.0) -> float:
        """Get the radial extent of the laser pulse in meters.

        Args:
            simulation_extent: (tuple[float, float]) The extent of the full simulation in meters.
            num_sigma: (float) Number of sigmas to account for in the radial extent.

        Returns:
            float: The radial extent of the laser pulse in meters."""
        ...
    @abstractmethod
    def resolve_laser_energy(self) -> float:
        """Resolve the laser energy from the laser pulse parameters."""
        ...
    @abstractmethod
    def resolve_laser_a0(self) -> float:
        """Resolve the laser a0 from the laser pulse parameters."""
        ...
    @abstractmethod
    def build_laser_profile(self) -> LaserProfile | list[LaserProfile]:
        """Return a LaserProfile object or list of LaserProfile objects that represents the laser pulse."""
        ...

class LasyLaserPulse(_LaserPulse):
    """Laser pulse from a `Lasy` profile.
    This is not yet implemented!

    Args:
        energy: (float|None) [J] |OPTIONAL| Energy of the laser pulse in Joules. Provide this or a0, not both.
        a0: (float|None) |OPTIONAL| Normalized laser amplitude parameter. Provide this or energy, not both.
        z0: (float) [m] Position of the laser pulse within the simulation window in meters.
        method: (Literal["direct", "antenna"]|None) |OPTIONAL| Method to use for laser pulse propagation. If None, the laser pulse will be propagated using the direct method.
        z0_antenna: (float|None) [m] |OPTIONAL| Position of the antenna within the simulation window in meters. Required if method is "antenna".
        v_antenna: (float|None) [m/s] |OPTIONAL| Velocity of the antenna in meters per second. Required if method is "antenna"."""
    SUBCLASS: ClassVar[str]
    def __init__(
        self,
        *,
        energy: float | None = None,
        a0: float | None = None,
        z0: float,
        method: Literal['direct', 'antenna'] | None = None,
        z0_antenna: float | None = None,
        v_antenna: float | None = None,
    ) -> None:
        """Laser pulse from a `Lasy` profile.
        This is not yet implemented!

        Args:
            energy: (float|None) [J] |OPTIONAL| Energy of the laser pulse in Joules. Provide this or a0, not both.
            a0: (float|None) |OPTIONAL| Normalized laser amplitude parameter. Provide this or energy, not both.
            z0: (float) [m] Position of the laser pulse within the simulation window in meters.
            method: (Literal["direct", "antenna"]|None) |OPTIONAL| Method to use for laser pulse propagation. If None, the laser pulse will be propagated using the direct method.
            z0_antenna: (float|None) [m] |OPTIONAL| Position of the antenna within the simulation window in meters. Required if method is "antenna".
            v_antenna: (float|None) [m/s] |OPTIONAL| Velocity of the antenna in meters per second. Required if method is "antenna"."""
    def get_r_extent(self, simulation_extent: tuple[float, float], num_sigma: float=3.0) -> float:
        ...
    def get_z_extent(self, num_sigma: float=3.0) -> tuple[float, float]:
        ...
    def resolve_laser_energy(self) -> float:
        ...
    def resolve_laser_a0(self) -> float:
        ...
    def build_laser_profile(self) -> LaserProfile | list[LaserProfile]:
        ...

class _GaussianTemporalLaserPulse(_LaserPulse):
    """Laser pulse with an explicit Gaussian temporal (longitudinal) profile.
    No transverse profile is defined; do not build this abstract class.

    Args:
        energy: (float|None) [J] |OPTIONAL| Energy of the laser pulse in Joules. Provide this or a0, not both.
        a0: (float|None) |OPTIONAL| Normalized laser amplitude parameter. Provide this or energy, not both.
        z0: (float) [m] Position of the laser pulse within the simulation window in meters.
        method: (Literal["direct", "antenna"]|None) |OPTIONAL| Method to use for laser pulse propagation. If None, the laser pulse will be propagated using the direct method.
        z0_antenna: (float|None) [m] |OPTIONAL| Position of the antenna within the simulation window in meters. Required if method is "antenna".
        v_antenna: (float|None) [m/s] |OPTIONAL| Velocity of the antenna in meters per second. Required if method is "antenna".
        wavelength: (float) [m] Wavelength of the laser pulse in meters.
        tau_fwhm: (float) [s] Full-width at half-maximum temporal duration of the laser pulse in seconds.
        cep: (float) [rad] Carrier envelope phase of the laser pulse in radians.
        waist: (float) [m] Waist radius of the laser pulse in meters.
        focal_position: (float) [m] Focal position of the laser pulse in meters.
        polarization: (float|tuple[float, float]|Literal["left", "right"]) [rad] Polarization angle of the laser pulse in radians.
            If a float is provided, it is interpreted as the polarization angle theta in the x-y plane.
            If a tuple is provided, it is interpreted as the Jones vector angles (theta, beta) with:
                a_x = a_0 * cos(theta) * phi(z,t)
                a_y = a_0 * sin(theta) * exp(i beta) * phi(z,t)
                phi(z,t) = exp(i (2pi/lambda) (z - z0) + i (omega t - cep))
                e.g., (pi/4,0) is linear polarization at 45 degrees to x, (pi/4, pi/2) is right circular polarization
            If "left" is provided, it is interpreted as a left-hand circular polarization with maximum laser parameter a0/sqrt(2).
            If "right" is provided, it is interpreted as a right-hand circular polarization with maximum laser parameter a0/sqrt(2)."""
    wavelength: float
    tau_fwhm: float
    cep: float
    waist: float
    focal_position: float
    polarization: float | tuple[float, float] | Literal['left', 'right']
    def __init__(
        self,
        *,
        energy: float | None = None,
        a0: float | None = None,
        z0: float,
        method: Literal['direct', 'antenna'] | None = None,
        z0_antenna: float | None = None,
        v_antenna: float | None = None,
        wavelength: float,
        tau_fwhm: float,
        cep: float,
        waist: float,
        focal_position: float,
        polarization: float | tuple[float, float] | Literal['left', 'right'],
    ) -> None:
        """Laser pulse with an explicit Gaussian temporal (longitudinal) profile.
        No transverse profile is defined; do not build this abstract class.

        Args:
            energy: (float|None) [J] |OPTIONAL| Energy of the laser pulse in Joules. Provide this or a0, not both.
            a0: (float|None) |OPTIONAL| Normalized laser amplitude parameter. Provide this or energy, not both.
            z0: (float) [m] Position of the laser pulse within the simulation window in meters.
            method: (Literal["direct", "antenna"]|None) |OPTIONAL| Method to use for laser pulse propagation. If None, the laser pulse will be propagated using the direct method.
            z0_antenna: (float|None) [m] |OPTIONAL| Position of the antenna within the simulation window in meters. Required if method is "antenna".
            v_antenna: (float|None) [m/s] |OPTIONAL| Velocity of the antenna in meters per second. Required if method is "antenna".
            wavelength: (float) [m] Wavelength of the laser pulse in meters.
            tau_fwhm: (float) [s] Full-width at half-maximum temporal duration of the laser pulse in seconds.
            cep: (float) [rad] Carrier envelope phase of the laser pulse in radians.
            waist: (float) [m] Waist radius of the laser pulse in meters.
            focal_position: (float) [m] Focal position of the laser pulse in meters.
            polarization: (float|tuple[float, float]|Literal["left", "right"]) [rad] Polarization angle of the laser pulse in radians.
                If a float is provided, it is interpreted as the polarization angle theta in the x-y plane.
                If a tuple is provided, it is interpreted as the Jones vector angles (theta, beta) with:
                    a_x = a_0 * cos(theta) * phi(z,t)
                    a_y = a_0 * sin(theta) * exp(i beta) * phi(z,t)
                    phi(z,t) = exp(i (2pi/lambda) (z - z0) + i (omega t - cep))
                    e.g., (pi/4,0) is linear polarization at 45 degrees to x, (pi/4, pi/2) is right circular polarization
                If "left" is provided, it is interpreted as a left-hand circular polarization with maximum laser parameter a0/sqrt(2).
                If "right" is provided, it is interpreted as a right-hand circular polarization with maximum laser parameter a0/sqrt(2)."""
    def plot(self, *, mode: Literal['lineout', 'lineout_and_2d']='lineout_and_2d', ax: 'plt.Axes | None'=None, num: int=600, output_path: Path | str | None=None, show: bool=False, label: str | None=None) -> 'plt.Figure':
        """Plot the laser pulse envelope and (optionally) a face-on x-y cross-section.

        Args:
            mode: (Literal["lineout", "lineout_and_2d"]) Panel layout.
                ``"lineout"`` shows only the longitudinal envelope.
                ``"lineout_and_2d"`` (default) adds a face-on x-y field-amplitude
                map at the focal plane with a quiver overlay showing polarization.
            ax: (matplotlib.axes.Axes|None) If provided, the longitudinal envelope
                is also drawn on this external axes (for combined overlay figures).
            num: (int) Grid resolution along each axis.
            output_path: (Path|str|None) If given, the figure is saved here.
            show: (bool) Whether to call ``plt.show()``.
            label: (str|None) Label for the external *ax* lineout. Defaults to
                ``SUBCLASS (polarization)``.

        Returns:
            The created matplotlib Figure."""
        ...

class GaussianLaserPulse(_GaussianTemporalLaserPulse):
    """Temporal-gaussian laser pulse with a Gaussian transverse profile.

    Args:
        energy: (float|None) [J] |OPTIONAL| Energy of the laser pulse in Joules. Provide this or a0, not both.
        a0: (float|None) |OPTIONAL| Normalized laser amplitude parameter. Provide this or energy, not both.
        z0: (float) [m] Position of the laser pulse within the simulation window in meters.
        method: (Literal["direct", "antenna"]|None) |OPTIONAL| Method to use for laser pulse propagation. If None, the laser pulse will be propagated using the direct method.
        z0_antenna: (float|None) [m] |OPTIONAL| Position of the antenna within the simulation window in meters. Required if method is "antenna".
        v_antenna: (float|None) [m/s] |OPTIONAL| Velocity of the antenna in meters per second. Required if method is "antenna".
        wavelength: (float) [m] Wavelength of the laser pulse in meters.
        tau_fwhm: (float) [s] Full-width at half-maximum temporal duration of the laser pulse in seconds.
        cep: (float) [rad] Carrier envelope phase of the laser pulse in radians.
        waist: (float) [m] Waist radius of the laser pulse in meters.
        focal_position: (float) [m] Focal position of the laser pulse in meters.
        polarization: (float|tuple[float, float]|Literal["left", "right"]) [rad] Polarization angle of the laser pulse in radians.
            If a float is provided, it is interpreted as the polarization angle theta in the x-y plane.
            If a tuple is provided, it is interpreted as the Jones vector angles (theta, beta) with:
                a_x = a_0 * cos(theta) * phi(z,t)
                a_y = a_0 * sin(theta) * exp(i beta) * phi(z,t)
                phi(z,t) = exp(i (2pi/lambda) (z - z0) + i (omega t - cep))
                e.g., (pi/4,0) is linear polarization at 45 degrees to x, (pi/4, pi/2) is right circular polarization
            If "left" is provided, it is interpreted as a left-hand circular polarization with maximum laser parameter a0/sqrt(2).
            If "right" is provided, it is interpreted as a right-hand circular polarization with maximum laser parameter a0/sqrt(2)."""
    SUBCLASS: ClassVar[str]
    def __init__(
        self,
        *,
        energy: float | None = None,
        a0: float | None = None,
        z0: float,
        method: Literal['direct', 'antenna'] | None = None,
        z0_antenna: float | None = None,
        v_antenna: float | None = None,
        wavelength: float,
        tau_fwhm: float,
        cep: float,
        waist: float,
        focal_position: float,
        polarization: float | tuple[float, float] | Literal['left', 'right'],
    ) -> None:
        """Temporal-gaussian laser pulse with a Gaussian transverse profile.

        Args:
            energy: (float|None) [J] |OPTIONAL| Energy of the laser pulse in Joules. Provide this or a0, not both.
            a0: (float|None) |OPTIONAL| Normalized laser amplitude parameter. Provide this or energy, not both.
            z0: (float) [m] Position of the laser pulse within the simulation window in meters.
            method: (Literal["direct", "antenna"]|None) |OPTIONAL| Method to use for laser pulse propagation. If None, the laser pulse will be propagated using the direct method.
            z0_antenna: (float|None) [m] |OPTIONAL| Position of the antenna within the simulation window in meters. Required if method is "antenna".
            v_antenna: (float|None) [m/s] |OPTIONAL| Velocity of the antenna in meters per second. Required if method is "antenna".
            wavelength: (float) [m] Wavelength of the laser pulse in meters.
            tau_fwhm: (float) [s] Full-width at half-maximum temporal duration of the laser pulse in seconds.
            cep: (float) [rad] Carrier envelope phase of the laser pulse in radians.
            waist: (float) [m] Waist radius of the laser pulse in meters.
            focal_position: (float) [m] Focal position of the laser pulse in meters.
            polarization: (float|tuple[float, float]|Literal["left", "right"]) [rad] Polarization angle of the laser pulse in radians.
                If a float is provided, it is interpreted as the polarization angle theta in the x-y plane.
                If a tuple is provided, it is interpreted as the Jones vector angles (theta, beta) with:
                    a_x = a_0 * cos(theta) * phi(z,t)
                    a_y = a_0 * sin(theta) * exp(i beta) * phi(z,t)
                    phi(z,t) = exp(i (2pi/lambda) (z - z0) + i (omega t - cep))
                    e.g., (pi/4,0) is linear polarization at 45 degrees to x, (pi/4, pi/2) is right circular polarization
                If "left" is provided, it is interpreted as a left-hand circular polarization with maximum laser parameter a0/sqrt(2).
                If "right" is provided, it is interpreted as a right-hand circular polarization with maximum laser parameter a0/sqrt(2)."""
    def get_r_extent(self, simulation_extent: tuple[float, float], num_sigma: float=3.0) -> float:
        ...
    def resolve_laser_energy(self) -> float:
        ...
    def resolve_laser_a0(self) -> float:
        ...
    def build_laser_profile(self) -> LaserProfile | list[LaserProfile]:
        ...
