# Auto-generated by tools/sync_config_docstrings.py — do not edit by hand.

from __future__ import annotations

from inversion_fbpic.lib.commented_yaml import YamlDescriptionMap, YamlDescriptions, YamlPath, dump_yaml_with_comments, extract_yaml_comments
from pathlib import Path
from typing import Any, ClassVar

class SerializableConfig:
    """Base class for serializable configurations.
    Supports serialization to and from JSON and YAML."""
    CONFIG_TYPE: ClassVar[str]
    SUBCLASS: ClassVar[str]
    yaml_class_description: str | None
    yaml_parameter_descriptions: dict[str, list[str]] | None
    yaml_description_map: dict[YamlPath, YamlDescriptions] | None
    source_file: Path | None
    def to_dict(self, *, include_nones: bool=True) -> dict[str, Any]:
        """Serialize this configuration to a JSON-friendly dictionary."""
        ...
    @classmethod
    def from_dict(cls, payload: dict[str, Any], *, overrides: dict[str, Any] | None=None) -> 'SerializableConfig':
        """Deserialize any registered configuration subclass from a dictionary.

        Args:
            payload: The dictionary to deserialize.
            overrides: Optional values merged into *payload* before deserialization.
                Nested dicts are merged recursively (e.g. ``{"parameters": {"energy": 1.0}}``).

        Returns:
            The deserialized configuration object."""
        ...
    @classmethod
    def example_dict(cls, *, include_nones: bool=True) -> dict[str, Any]:
        """Build an example payload dict with default values for each init field.

        Intended for concrete subclasses. Fields with an explicit attrs default
        use that value (e.g. optional ``str | None`` with default ``"H"``).
        Otherwise each field type is mapped to a sensible zero-value (float ->
        0.0, str -> "", int -> 0, etc.). Optional (union with None) fields
        without an explicit default use null.

        Returns:
            The example payload dictionary."""
        ...
    @classmethod
    def example_json(cls, file_name: str | Path | None=None, *, indent: int=2, include_nones: bool=True) -> str:
        """Return an example JSON serialization with default values for each field.

        Args:
            file_name: The file to write the example JSON to. If None, it is not written to a file. Defaults to None.
            indent: The indentation level for the JSON. Defaults to 2.

        Returns:
            The example JSON string."""
        ...
    @classmethod
    def from_json(cls, payload: str, *, overrides: dict[str, Any] | None=None) -> 'SerializableConfig':
        """Deserialize a configuration from a JSON string.

        Args:
            payload: The JSON string to deserialize.
            overrides: Optional values merged into the parsed payload before
                deserialization. See :meth:`from_dict`.

        Returns:
            The deserialized configuration object."""
        ...
    def to_json(self, *, indent: int=2, include_nones: bool=True) -> str:
        """Serialize this configuration to a JSON string.

        Args:
            indent: The indentation level for the JSON. Defaults to 2.

        Returns:
            The JSON string."""
        ...
    def to_json_file(self, path: str | Path, *, indent: int=2, include_nones: bool=True) -> Path:
        """Write this configuration to a JSON file.

        Args:
            path: The path to the JSON file to write.
            indent: The indentation level for the JSON. Defaults to 2.

        Returns:
            The path to the written JSON file."""
        ...
    @classmethod
    def example_yaml(cls, file_name: str | Path | None=None, *, indent: int=2, comments: bool=True, include_nones: bool=True, nested_flow_style: bool=True) -> str:
        """Return an example YAML serialization with default values for each field.

        Args:
            file_name: The file to write the example YAML to. If None, it is not written to a file. Defaults to None.
            indent: The indentation level for the YAML. Defaults to 2.
            comments: Whether to include comments in the YAML. Defaults to True.
            nested_flow_style: Whether nested dict and list attrs use YAML flow
                style. Defaults to True.

        Returns:
            The example YAML string."""
        ...
    @classmethod
    def from_yaml(cls, payload: str, *, overrides: dict[str, Any] | None=None) -> 'SerializableConfig':
        """Deserialize a configuration from a YAML string.

        Inline and block ``#`` comments in the source are stored on the returned
        instance for round-trip serialization via :meth:`to_yaml`.

        Args:
            payload: The YAML string to deserialize.
            overrides: Optional values merged into the parsed payload before
                deserialization. See :meth:`from_dict`.

        Returns:
            The deserialized configuration object."""
        ...
    def to_yaml(self, *, indent: int=2, comments: bool=True, round_trip_comments: bool=True, include_nones: bool=True, nested_flow_style: bool=True) -> str:
        """Serialize this configuration to a YAML string.

        Args:
            indent: The indentation level for the YAML. Defaults to 2.
            comments: Whether to include comments in the YAML. Defaults to True.
            round_trip_comments: When ``True`` and this instance was loaded from
                commented YAML, emit those stored comments; otherwise use
                docstring-derived comments. Ignored when ``comments`` is ``False``.
            nested_flow_style: Whether nested dict and list attrs use YAML flow
                style. Defaults to True.

        Returns:
            The YAML string."""
        ...
    def to_yaml_file(self, path: str | Path, *, indent: int=2, comments: bool=True, round_trip_comments: bool=True, include_nones: bool=True, nested_flow_style: bool=True) -> Path:
        """Serialize this configuration to a YAML file.

        Args:
            path: The path to the YAML file to write.
            indent: The indentation level for the YAML. Defaults to 2.
            comments: Whether to include comments in the YAML. Defaults to True.
            round_trip_comments: When ``True`` and this instance was loaded from
                commented YAML, emit those stored comments; otherwise use
                docstring-derived comments.
            nested_flow_style: Whether nested dict and list attrs use YAML flow
                style. Defaults to True.

        Returns:
            The path to the written YAML file."""
        ...
    @classmethod
    def resolving_paths_relative_to(cls, directory: str | Path):
        """Resolve nested config path strings relative to *directory* within the block."""
        ...
    @classmethod
    def from_file(cls, path: str | Path, *, relative_to: Path | None=None, overrides: dict[str, Any] | None=None) -> 'SerializableConfig':
        """Deserialize a configuration from a file.

        Relative paths are resolved against *relative_to* when provided, otherwise
        against the directory of the config file currently being loaded (for nested
        references), and finally against the process working directory.

        Args:
            path: Path to a ``.json``, ``.jsn``, ``.yaml``, or ``.yml`` config file.
            relative_to: Optional base directory for resolving a relative *path*.
            overrides: Optional values merged into the file payload before
                deserialization. See :meth:`from_dict`."""
        ...
    @classmethod
    def from_any(cls, value: 'SerializableConfig | str | Path | dict[str, Any]', *, relative_to: Path | None=None, overrides: dict[str, Any] | None=None) -> 'SerializableConfig':
        """Deserialize a configuration from any supported source.

        Resolution order:

        1. Return *value* unchanged if it is already a :class:`SerializableConfig`.
        2. Load from a file when *value* is a :class:`~pathlib.Path`.
        3. Deserialize from a mapping when *value* is a ``dict``.
        4. For a ``str``, try loading from a file path first; otherwise parse
           as YAML or JSON and deserialize the resulting mapping.
        5. Raise :class:`TypeError` for unsupported types.

        Args:
            value: An existing config, file path, mapping, or serialized string.
            relative_to: Optional base directory for resolving a relative path.
            overrides: Optional values merged into the payload before
                deserialization. See :meth:`from_dict`."""
        ...
