# Auto-generated by tools/sync_config_docstrings.py — do not edit by hand.

from __future__ import annotations

from .density_core import _DensityProfile
from .laser import _LaserPulse
from .serializable_config import SerializableConfig
from fbpic.main import Simulation as FBPICSimulation, Particles
from pathlib import Path
from typing import ClassVar, Literal, List, Any
import logging

class Simulation(SerializableConfig):
    """Simulation class for FBPIC simulations.

    Args:
        elements: (str | Path | SerializableConfig | List[str | Path | SerializableConfig]) The elements of the simulation. May be a path to a YAML or JSON file or objects of type SimulationHyperparameters, DensityProfile, or LaserPulse.
        verbosity: (int) |OPTIONAL| The verbosity of the logger. Defaults to 20 (INFO)."""
    CONFIG_TYPE: ClassVar[str]
    SUBCLASS: ClassVar[str]
    elements: str | Path | dict[str, Any] | SerializableConfig | List[str | Path | dict[str, Any] | SerializableConfig]
    verbosity: int
    hyparams: SimulationHyperparameters | None
    densities: List[_DensityProfile]
    lasers: List[_LaserPulse]
    simulation: FBPICSimulation
    working_directory: Path
    is_setup: bool
    T_interact: float
    def __init__(
        self,
        *,
        elements: str | Path | dict[str, Any] | SerializableConfig | List[str | Path | dict[str, Any] | SerializableConfig],
        verbosity: int = logging.INFO,
    ) -> None:
        """Simulation class for FBPIC simulations.

        Args:
            elements: (str | Path | SerializableConfig | List[str | Path | SerializableConfig]) The elements of the simulation. May be a path to a YAML or JSON file or objects of type SimulationHyperparameters, DensityProfile, or LaserPulse.
            verbosity: (int) |OPTIONAL| The verbosity of the logger. Defaults to 20 (INFO)."""
    @property
    def z_extent(self) -> tuple[float, float]:
        """The extent of the simulation."""
        ...
    @property
    def do_write_to_disk(self) -> bool:
        """Determines whether it is safe to handle output to disk when MPI is in use."""
        ...
    def config_hash(self) -> str:
        """Return a stable SHA-256 hex digest of this simulation's configuration.

        The hash is independent of the order in which elements were provided."""
        ...
    @staticmethod
    def calculate_group_beta(wavelength: float, plasma_density: float) -> float:
        """Calculate the group velocity (normalized to the speed of light) of electromagnetic waves in a plasma.

        Args:
            wavelength: (float) [m] The wavelength of the EM wave.
            plasma_density: (float) [m^-3] The density of the plasma.

        Returns:
            (float) [c] The group velocity of the EM wave in the plasma normalized to c."""
        ...
    def calculate_mean_group_beta(self, wavelength: float | None=None, num_samples: int=1000) -> float:
        """Calculate the mean group velocity of EM waves in this `Simulation`'s on-axis plasma profile.
        This is the total simulation length (maximal extent) divided by the time to traverse.

        Args:
            wavelength: (float) [m] |OPTIONAL| The wavelength of the EM wave. If None, the wavelength is calculated from the mean group velocity of the first laser to have a `wavelength` attribute.
            num_samples: (int) |OPTIONAL| Number of samples to take along the plasma profile. Defaults to 1000.
        Returns:
            (float) [c] The mean group velocity of the EM wave in the plasma normalized to c."""
        ...
    @property
    def num_steps(self) -> int:
        """Number of FBPIC iterations required for the interaction."""
        ...
    def setup_simulation(self, working_directory: Path | str | None=None, skip_if_hashed: bool=True, **kwargs) -> None:
        """Setup the simulation.

        Args:
            working_directory: (str | Path | None) |OPTIONAL| The working directory to save the simulation. If None, the working directory is the current working directory.
            skip_if_hashed: (bool) |OPTIONAL| Whether to skip the setup if there is a recorded hash that matches the current simulation configuration. Defaults to True.
            **kwargs: Additional keyword arguments for the simulation setup, passed to FBPIC's `Simulation` constructor.

        Returns:
            None"""
        ...
    def run_simulation(self, show_progress: bool=True, logger_friendly_progress: bool=False, record_hash: bool=True, skip_if_hashed: bool=True) -> None:
        """Run the simulation. `setup_simulation()` must be called before this function.

        Args:
            show_progress: (bool) Whether to show the progress bar. Defaults to True.
            logger_friendly_progress: (bool) Whether to use logger-friendly output for indicating progress. Defaults to False.
            record_hash: (bool) Whether to record the hash of the simulation configuration upon successful completion. Defaults to True.
            skip_if_hashed: (bool) Whether to skip the simulation if the configuration hash is the same as a previous run. Defaults to True.

        Returns:
            None"""
        ...

class SimulationHyperparameters(SerializableConfig):
    """Hyperparameters for FBPIC simulations.

    Args:
        zmin: (float) [m] Minimum z position of the simulation box.
        zmax: (float) [m] Maximum z position of the simulation box.
        rmax: (float) [m] Maximum radial position of the simulation box.
        nz: (int) Number of gridpoints along the longitudinal direction. This should optimally have a small greatest-prime-factor for FFT performance.
        nr: (int) Number of gridpoints along the radial direction.
        nm: (int) Number of angular modes used.
        use_mpi: (bool) Whether to use MPI.
        number_dumps: (int) Number of diagnostic dumps to save.
        right_buffer: (float | None) |OPTIONAL| Right buffer of the simulation extent. If None, equal to the window size (zmax - zmin).
        beta_window: (float | None) |OPTIONAL| Beta of the moving window. If None, the moving window velocity is calculated to be the group velocity of
            the first LaserPulse object with a `wavelength` data attribute in conjunction with the combination of all nominal plasma densities.
            If no `wavelength` attribute is found, the moving window velocity is set to 1.0.
        gamma_boost: (float | None) |OPTIONAL| Gamma boost factor.
        field_diagnostics: (list[Literal["rho", "E", "B", "J"]] | None) |OPTIONAL| List of field diagnostics to save. If None, no field diagnostics are saved.
        save_directory: (str | Path) |OPTIONAL| Directory to save the diagnostics. If not absolute, this is relative to the `working_directory` passed to `Simulation.setup_simulation()`. Defaults to "diags".
        save_checkpoints: (bool) |OPTIONAL| Whether to save checkpoints. Defaults to False.
        checkpoint_period: (int) |OPTIONAL| Period to save checkpoints. Defaults to 100.
        write_period: (int) |OPTIONAL| Period to write diagnostics to disk. Defaults to 50.
        use_restart: (bool) |OPTIONAL| Whether to restart from a checkpoint. Defaults to False.
        track_electrons: (bool) |OPTIONAL| Whether to track and write particle ids. Defaults to False.
        n_order_mpi: (int) |OPTIONAL| Order of the stencil for z derivatives in the Maxwell solver if using MPI parallelization. Defaults to 32.
        random_seed: (int | None) |OPTIONAL| Random seed. Defaults to None (unset).
        r_boundary: (Literal["open", "reflective"]) |OPTIONAL| Boundary condition for the radial direction. Defaults to "reflective"."""
    CONFIG_TYPE: ClassVar[str]
    SUBCLASS: ClassVar[str]
    zmin: float
    zmax: float
    rmax: float
    nz: int
    nr: int
    nm: int
    use_mpi: bool
    number_dumps: int
    right_buffer: float | None
    beta_window: float | None
    gamma_boost: float | None
    field_diagnostics: list[Literal['rho', 'E', 'B', 'J']] | None
    save_directory: Path
    save_checkpoints: bool
    checkpoint_period: int
    write_period: int
    use_restart: bool
    track_electrons: bool
    n_order_mpi: int
    random_seed: int | None
    r_boundary: Literal['open', 'reflective']
    def __init__(
        self,
        *,
        zmin: float,
        zmax: float,
        rmax: float,
        nz: int,
        nr: int,
        nm: int,
        use_mpi: bool,
        number_dumps: int,
        right_buffer: float | None = None,
        beta_window: float | None = None,
        gamma_boost: float | None = None,
        field_diagnostics: list[Literal['rho', 'E', 'B', 'J']] | None = None,
        save_directory: Path = Path('diags'),
        save_checkpoints: bool = False,
        checkpoint_period: int = 100,
        write_period: int = 50,
        use_restart: bool = False,
        track_electrons: bool = False,
        n_order_mpi: int = 32,
        random_seed: int | None = None,
        r_boundary: Literal['open', 'reflective'] = 'reflective',
    ) -> None:
        """Hyperparameters for FBPIC simulations.

        Args:
            zmin: (float) [m] Minimum z position of the simulation box.
            zmax: (float) [m] Maximum z position of the simulation box.
            rmax: (float) [m] Maximum radial position of the simulation box.
            nz: (int) Number of gridpoints along the longitudinal direction. This should optimally have a small greatest-prime-factor for FFT performance.
            nr: (int) Number of gridpoints along the radial direction.
            nm: (int) Number of angular modes used.
            use_mpi: (bool) Whether to use MPI.
            number_dumps: (int) Number of diagnostic dumps to save.
            right_buffer: (float | None) |OPTIONAL| Right buffer of the simulation extent. If None, equal to the window size (zmax - zmin).
            beta_window: (float | None) |OPTIONAL| Beta of the moving window. If None, the moving window velocity is calculated to be the group velocity of
                the first LaserPulse object with a `wavelength` data attribute in conjunction with the combination of all nominal plasma densities.
                If no `wavelength` attribute is found, the moving window velocity is set to 1.0.
            gamma_boost: (float | None) |OPTIONAL| Gamma boost factor.
            field_diagnostics: (list[Literal["rho", "E", "B", "J"]] | None) |OPTIONAL| List of field diagnostics to save. If None, no field diagnostics are saved.
            save_directory: (str | Path) |OPTIONAL| Directory to save the diagnostics. If not absolute, this is relative to the `working_directory` passed to `Simulation.setup_simulation()`. Defaults to "diags".
            save_checkpoints: (bool) |OPTIONAL| Whether to save checkpoints. Defaults to False.
            checkpoint_period: (int) |OPTIONAL| Period to save checkpoints. Defaults to 100.
            write_period: (int) |OPTIONAL| Period to write diagnostics to disk. Defaults to 50.
            use_restart: (bool) |OPTIONAL| Whether to restart from a checkpoint. Defaults to False.
            track_electrons: (bool) |OPTIONAL| Whether to track and write particle ids. Defaults to False.
            n_order_mpi: (int) |OPTIONAL| Order of the stencil for z derivatives in the Maxwell solver if using MPI parallelization. Defaults to 32.
            random_seed: (int | None) |OPTIONAL| Random seed. Defaults to None (unset).
            r_boundary: (Literal["open", "reflective"]) |OPTIONAL| Boundary condition for the radial direction. Defaults to "reflective"."""
    def grid_parameters_yaml(self, file_name: str | None=None, comments: bool=True, indent: int=2) -> str:
        """Grid parameters for the simulation. Returns a YAML string of the grid parameters.
        If a file name is provided, the YAML string is written to the file.

        Args:
            file_name: The file to write the YAML string to. If None, the YAML string is not written to a file. Defaults to None.
            comments: Whether to include comments in the YAML. Defaults to True.
            indent: The indentation level for the YAML. Defaults to 2.

        Returns:
            str: A YAML string of the grid parameters."""
        ...
    @property
    def is_boosted(self) -> bool:
        """Whether this simulation is boosted."""
        ...
    @property
    def n_order(self) -> int:
        """Order of the stencil for z derivatives in the Maxwell solver."""
        ...
    @property
    def dt(self) -> float:
        """Timestep for the simulation."""
        ...
    @property
    def v_comoving(self) -> float:
        """Velocity of the Galilean frame (for suppression of the NCI)."""
        ...
    @property
    def dz(self) -> float:
        """Grid spacing along the longitudinal direction."""
        ...
    @property
    def dr(self) -> float:
        """Grid spacing along the radial direction."""
        ...
    @property
    def do_write_to_disk(self) -> bool:
        """Determines whether it is safe to handle output to disk when MPI is in use."""
        ...

class _GridParameters(SerializableConfig):
    """Grid parameters for the simulation.

    Args:
        dt: (float) [s] Timestep for the simulation.
        dz: (float) [m] Grid spacing along the longitudinal direction.
        dr: (float) [m] Grid spacing along the radial direction.
        nz: (int) Number of gridpoints along the longitudinal direction.
        nr: (int) Number of gridpoints along the radial direction.
        nm: (int) Number of angular modes used. Defaults to 3.
        zmin: (float) [m] Minimum z position of the simulation box.
        zmax: (float) [m] Maximum z position of the simulation box.
        rmax: (float) [m] Maximum radial position of the simulation box.
        gamma_boost: (float | None) |OPTIONAL| Gamma boost factor. Defaults to None."""
    CONFIG_TYPE: ClassVar[str]
    SUBCLASS: ClassVar[str]
    dt: float
    dz: float
    dr: float
    nz: int
    nr: int
    nm: int
    zmin: float
    zmax: float
    rmax: float
    gamma_boost: float | None
    def __init__(
        self,
        *,
        dt: float,
        dz: float,
        dr: float,
        nz: int,
        nr: int,
        nm: int,
        zmin: float,
        zmax: float,
        rmax: float,
        gamma_boost: float | None = None,
    ) -> None:
        """Grid parameters for the simulation.

        Args:
            dt: (float) [s] Timestep for the simulation.
            dz: (float) [m] Grid spacing along the longitudinal direction.
            dr: (float) [m] Grid spacing along the radial direction.
            nz: (int) Number of gridpoints along the longitudinal direction.
            nr: (int) Number of gridpoints along the radial direction.
            nm: (int) Number of angular modes used. Defaults to 3.
            zmin: (float) [m] Minimum z position of the simulation box.
            zmax: (float) [m] Maximum z position of the simulation box.
            rmax: (float) [m] Maximum radial position of the simulation box.
            gamma_boost: (float | None) |OPTIONAL| Gamma boost factor. Defaults to None."""
